### ISSUE TITLE
Error on restart

### ISSUE THREAD

**Issue by yolani** [JimStar/reolink_cctv#106]
**Describe the bug**
Whenever I restart my home assistant installation with this integration enabled, I get an error log regarding an erroneous usage of the ReolinkHost API.

**To Reproduce**
Enable integration, restart HA

**Expected behavior**
No error log, clean shutdown

**Debug log would be very helpful**
--- Message -------------------------------
Error doing job: Exception in callback ReolinkHost.stop(<Event homeassistant_stop[L]>)
--- Exception -----------------------------
Traceback (most recent call last):
 File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
   self._context.run(self._callback, *self._args)
 File "/usr/src/homeassistant/homeassistant/core.py", line 1051, in _onetime_listener
   self._hass.async_run_job(listener, event)
 File "/usr/src/homeassistant/homeassistant/core.py", line 622, in async_run_job
   return self.async_run_hass_job(HassJob(target), *args)
 File "/usr/src/homeassistant/homeassistant/core.py", line 577, in async_run_hass_job
   return self.async_add_hass_job(hassjob, *args)
 File "/usr/src/homeassistant/homeassistant/core.py", line 480, in async_add_hass_job
   task = self.loop.create_task(hassjob.target(*args))
TypeError: ReolinkHost.stop() takes 1 positional argument but 2 were given

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version: 2022.12.0
 - Reolink NVR/camera model: RLC-810A
 - NVR/camera firmware v3.1.0.764_22022803

**Additional context**
Maybe any other context about the problem here.

**Comment by JimStar** [comment]
Looks like some changes in a new HA version... Have you maybe updated HA recently? If yes, was it OK before the update?
