### ISSUE TITLE
WebRTC stops working on Reolink cameras after update to v0.1.1

### ISSUE THREAD

**Issue by rhpijnacker** [JimStar/reolink_cctv#109]
Upgraded to v0.1.1 and now the camera entities no longer work with WebRTC (which was working fine).
I get the message "ERROR: Can't get URL for camera.xyz".

**To Reproduce**
Create a card with the following settings:
```
type: custom:webrtc-camera
entity: camera.xyz
```

**Expected behavior**
The WebRTC frame to show the camera feed

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version 2022 12.1
 - Reolink NVR RLN8-401 with 3 R420A cameras / POE Doorbell (same behaviour)

Reolink Video Doorbell PoE
Firmware: v3.0.0.1459_22102808
Hardware: DB_566128M5MP_P

RLN8-410
Firmware: v3.0.0.148_21101146
Hardware: N3MB01

**Comment by JimStar** [comment]
This is a major version change, which has some changes in how cameras' are formed.  
You need to re-create your cards, replacing the camera-id by the new ones.

Feel free to reopen this with the **full debug log** file attached, if you would still have the problem after that.

**Comment by rhpijnacker** [comment]
Updating the entiry worked for the Doorbell camera, which is directly connected to HA.
For the cameras behind the NVR, it did not work. It says "404 Stream not found"
Logging can be found at: https://controlc.com/52706dd9

**Comment by JimStar** [comment]
Have a look at this:  
[https://github.com/home-assistant/core/issues/42389](https://github.com/home-assistant/core/issues/42389)

**Comment by rhpijnacker** [comment]
Not sure what you suggest I do with that link.
For the Doorbell it is now working OK. So, the streaming part seems to be working.
I do not have a `.storage/camera` entry, like in the link. Just to try it out, I removed the `reolink_cctv` folder in there and reloaded the add-on. But that does not seem to make any difference.

**Comment by PedroQ** [comment]
I'm having this issue as well.

While trying to understand what could be happening, I notived this in the error logs:

> Logger: homeassistant.components.stream.stream.camera.lens_1_sub
Source: components/stream/__init__.py:434
Integration: Stream ([documentation](https://www.home-assistant.io/integrations/stream), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+stream%22))
First occurred: 03:24:42 (2 occurrences)
Last logged: 03:24:53
Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsp://\*\*\*\*:\*\*\*\*@192.168.27.11:554/Preview_01_sub

The stream URL that the integration is providing doesn't seem to be correct. Looking at [the documentation](https://support.reolink.com/hc/en-us/articles/360006240073-Request-for-RTSP-URL), it's missing the h264 prefix, so it should be rtsp://_username_:_password_@192.168.27.11:554/**h264**Preview_01_sub

**Comment by JimStar** [comment]
<img width="877" alt="Screen Shot 2022-12-11 at 16 46 08" src="https://user-images.githubusercontent.com/3421219/206885387-09b891e9-dc0f-42b1-be52-0a23fe1c3cf0.png">

**Comment by PedroQ** [comment]
I'm not questioning that it may have been deprecated, but old firmwares still require it and unless this change is introduced in future firmwares, it will still be required.

**Comment by JimStar** [comment]
Is the new firmware available for your camera?

**Comment by PedroQ** [comment]
I have an E1 Zoom, running the latest firmware (v3.0.0.1107).

**Comment by JimStar** [comment]
Are you sure the `rtsp://username:password@192.168.27.11:554/h264Preview_01_sub` address doesn't work if you try it in directly (e.g. using your browser)?

**Comment by JimStar** [comment]
Sorry, I've fixed a typo in above post: I meant the `rtsp://username:password@192.168.27.11:554/Preview_01_sub` address to try in the browser...

**Comment by PedroQ** [comment]
I tried with VLC. Only the URL with the h264 prefix works.

**Comment by JimStar** [comment]
OK, thanks. Looks like Reolink just abandoned their E1 cameras...  
I'll make a fix in the next version.

**Comment by JimStar** [comment]
Should be fixed in [0.1.3](https://github.com/JimStar/reolink_cctv/releases/tag/0.1.3).

**Comment by rhpijnacker** [comment]
After upgrading to 0.1.3 it works for me again too on the NVR.
