### ISSUE TITLE
Ability to support "Quick Reply" for Reolink Doorbell?

### ISSUE THREAD

**Issue by quizzical86** [JimStar/reolink_cctv#124]
The Reolink Doorbell has a feature called "[Quick Reply](https://support.reolink.com/hc/en-us/articles/11613139933465-How-to-Set-up-Quick-Reply-via-Reolink-App)". Using this feature you can get the doorbell to speak a pre-recorded message of your choice. There are a few built-in and you can record your own messages as well (e.g. I'm not home, leave the package at the door, i'll be there in a moment, etc).

Thanks to your integration, Home Assistant sends me a notification when someone's at the door together with a screenshot. It would be great if in that notification I could click on of those default messages.

Could that be possible? It looks like finding the right code by visiting  https://(cameraipaddress)?debug=1 won't work as this quick reply feature is not available in the browser. Only in the app and the client.
If it isn't possible, what should I ask Reolink to do on their end to get this working?

Thanks a lot!

**Comment by JimStar** [comment]
I could easily implement this if I knew the command that needs to be sent to a doorbell - and I don't see any description of such command in the current Reolink's API v7 reference. If there is no such function in its web-UI, then it could be problematic. Only if Reolink support would be wise enough to provide this command and its description...

**Comment by quizzical86** [comment]
OK thanks! I had already written to Reolink about this but gotten a strange reply (basically saying all they have is the V6 User Guide, while that one is already year old)
I have now written to them again. Fingers crossed and thanks for your advice!
The only alternative I can think of is to get Synology to properly integrate this camera into their NVR software which I'm using. I have other cameras that have two-way audio supported and there I can use Synology's software to then play audio files.

**Comment by timvdsm** [comment]
FYI ... I think you can activate the automatic auto-reply in general through the **webpage**. This is just activating the schedule, not manually sending the message.

The only thing I see is, but I guess this is not usefull:
Activate schedule auto reply message 1: after 2s
getQueryDataByCount: flagO=SetAutoReply&countIdO=28&checkNumO=38&queryStringO=&cmd=SetAutoReply

Desactivate schedule auto reply message 1: after 2s:
getQueryDataByCount: flagO=SetAutoReply&countIdO=6&checkNumO=37&queryStringO=&cmd=SetAutoReply

Activate schedule auto reply message 3: after 15s:
getQueryDataByCount: flagO=SetAutoReply&countIdO=29&checkNumO=40&queryStringO=&cmd=SetAutoReply

**If I set the schedule settings throught the reolink app,** I receive the following:
set through app: auto reply message 3 after 2 seconds:
getQueryDataByCount: flagO=GetAudioFileList&countIdO=4&checkNumO=43&queryStringO=&cmd=GetAudioFileList
getQueryDataByCount: flagO=GetAutoReply&countIdO=18&checkNumO=43&queryStringO=&cmd=GetAutoReply

set through app: auto reply message 3 after 5 seconds:
getQueryDataByCount: flagO=GetAudioFileList&countIdO=12&checkNumO=44&queryStringO=&cmd=GetAudioFileList
getQueryDataByCount: flagO=GetAutoReply&countIdO=15&checkNumO=47&queryStringO=&cmd=GetAutoReply

set through app: auto reply message 2 after 5 seconds:
getQueryDataByCount: flagO=GetAudioFileList&countIdO=11&checkNumO=46&queryStringO=&cmd=GetAudioFileList
getQueryDataByCount: flagO=GetAutoReply&countIdO=27&checkNumO=47&queryStringO=&cmd=GetAutoReply

set through app: auto reply message 1 after 5 seconds:
getQueryDataByCount: flagO=GetAudioFileList&countIdO=8&checkNumO=44&queryStringO=&cmd=GetAudioFileList
getQueryDataByCount: flagO=GetAutoReply&countIdO=15&checkNumO=48&queryStringO=&cmd=GetAutoReply

For me there is no logic, except for "supportAutoReply", "supportAudioFileList", "GetAudioFileList", "GetAutoReply", "SetAutoReply".

**Comment by quizzical86** [comment]
I didn't fully understand your post, but I understand you also conclude that it currently isn't possible to trigger a quick reply though the API :-(

**Comment by timvdsm** [comment]
We did some further troubleshooting with @mnpg. Thanks for the support!
https://github.com/mnpg/Reolink_api_documentations/issues/1
Keep in mind that this is the **automatic** auto-reply, which can be configured from the webUI and the reolink clients. It's a configuration where you define what reply message you want to trigger x seconds after someone pushes the doorbell. 
It's **not manually triggering a specific reply message**. That one needs some further investigation as it's only available through the reolink clients, not through the webUI. 

The following commands do exist for the auto reply: `GetAutoReply`, `SetAutoReply`, `GetAudioFileList`
For the `GetAudioFileList` I get the following (all configured reply messages):

```
[
{
"cmd" : "GetAudioFileList",
"code" : 0,
"initial" : {
"AudioFileList" : [
{
"audioLen" : 3,
"fileName" : "I'm sorry. I think you've knocked on the wrong door.",
"fileSize" : 30720,
"id" : 0,
"type" : "alarm"
},
{
"audioLen" : 4,
"fileName" : "Hi, we will be right there. Please wait a moment.",
"fileSize" : 32640,
"id" : 1,
"type" : "alarm"
},
{
"audioLen" : 4,
"fileName" : "Hi, please leave the package at the door. We will get it later.",
"fileSize" : 38720,
"id" : 2,
"type" : "alarm"
},
{
"audioLen" : 5,
"fileName" : "Achterlaten poortje",
"fileSize" : 46080,
"id" : 3,
"type" : "reply"
},
```

With the command `SetAutoReply`, you can set the status of the Auto Reply (ON/OFF) with the field `enable` and also the Audio File that you want to hear as a reply (field `fileId`) and the waiting time (field `timeout` -NB: time in seconds-)
`enable` : 0 (auto reply disabled) - 1 (auto reply enabled)
`fileID`: 0 - .... (ID of the reply message - it seems you can have 12 messages - need still some testing)
`timeout`: 2 - 5 - 10 - 15 - 20 (seconds)

Example:
`enable` = 1 (auto reply enabled) 
`fileId` = 3 that correspond with the field id from the `GetAudioFileList` and that was a message I created myself
`timeout`= 2 (as I want the automatic auto-reply to trigger 2 seconds after someones pushes the doorbell)

**In the command below, change #IP# to the IP address of the doorbell and#username# and #password# (an admin account credentials) by your own values. The URL is in https, change it to http if it doesn't work**

- set the auto-reply to OFF :
`curl -s -k -X POST -H "Content-Type : application/json" -d "[{\"cmd\":\"SetAutoReply\",\"action\":1,\"param\":{\"enable\":0,\"channel\":0}}]" "https://#IP#/cgi-bin/api.cgi?user=#USERNAME#&password=#PASSWORD#"`

- set the auto-reply to ON (with `fileID` 3 and `timeout` 2s):
`curl -s -k -X POST -H "Content-Type : application/json" -d "[{\"cmd\":\"SetAutoReply\",\"action\":0,\"param\":{\"AutoReply\":{\"enable\":1,\"fileId\":3,\"timeout\":2,\"channel\":0}}}]" "https://#IP#/cgi-bin/api.cgi?user=#USERNAME#&password=#PASSWORD#"`

- set the auto-reply to ON (with `fileID` 1 and `timeout` 15s):
`curl -s -k -X POST -H "Content-Type : application/json" -d "[{\"cmd\":\"SetAutoReply\",\"action\":0,\"param\":{\"AutoReply\":{\"enable\":1,\"fileId\":1,\"timeout\":15,\"channel\":0}}}]" "https://192.168.1.106/cgi-bin/api.cgi?user=admin&password=1Aazerty"`

- change the waiting time (to 20 seconds for example):
`curl -s -k -X POST -H "Content-Type : application/json" -d "[{\"cmd\":\"SetAudioReply\",\"action\":1,\"param\":{\"timeout\":20,\"channel\":0}}]" "https://#IP#/cgi-bin/api.cgi?user=#USERNAME#&password=#PASSWORD#"`

- change the audio message (for example : "Hi, please leave the package at the door. We will get it later." -id:2 take from the GetAudioFileList-) :
`curl -s -k -X POST -H "Content-Type : application/json" -d "[{\"cmd\":\"SetAudioReply\",\"action\":1,\"param\":{\"fileId\":2,\"channel\":0}}]" "https://#IP#/cgi-bin/api.cgi?user=#USERNAME#&password=#PASSWORD#"`

So I guess that's some good news. :-)

And once again credits to @mnpg
