### ISSUE TITLE
Internal IP address?

### ISSUE THREAD

**Issue by gcormier** [JimStar/reolink_cctv#125]
I noticed that the NVR will send an ONVIF notification to Home assistant from reading some of the reolink_cctv docs.

```
For the motion detection to work, Home Assistant must be reachable via HTTP from your local network. So when using HTTPS internally, motion detection will not work. This is the Reolink firmware bug: it fails to send ONVIF notifications to HTTPS webhooks.
```

I'm running HA in docker, so it's likely that it sees an internal docker IP address and not my local LAN 192.168.1.x address. Is there a way I can check, and a way we can add this?

To my knowledge this would not be the same as the `External IP` setting.

**Comment by JimStar** [comment]
Sorry but this is not related to this component's functionality, so it's not a reason for an issue-ticket. This is the matter of setting up your HA and your local network...  
Please feel free to ask for an advice of setting everything up in the "Discussions" section...
