### ISSUE TITLE
Reolink doorbell POE versions doesn't get the Button Pressed sensor status changed

### ISSUE THREAD

**Issue by MiAutomations** [JimStar/reolink_cctv#127]
Hello 

First of all thank you for this integration and your work on it 

I recently discover this integration and I'm searching for a way to integrate my Reolink POE version in to HA - Home Assistant.

I know that the Binary sensor works with the wi-fi version of this doorbell, but I can't receive the status changed of this sensor when I press the button on the POE doorbell  version.

As you can check, I already pressed several times the button, but I can't get the status ON on this binary sensor 

![image](https://user-images.githubusercontent.com/47602733/208412881-c9a5f983-88b3-44ec-a773-22fce23be68d.png)

I still only receiving the Off and the unavailable status and not the ON status 

I already try to fix this issue restart the Home Assistant, reload this integration, removed and added again the integrations wihout success until now...

Can you please help me in order to try solve this issue ?

Please let me know if you need any further information from my side 

Thank you in advance for your hep and best regards

**Comment by sanderlv** [comment]
May I ask, I read every post of the other ticket. But I was not finding a concrete answer to the above. Can you please help out what the solution is?
