### ISSUE TITLE
Reolink (PoE) doorbell - Reolink Video Doorbell Siren 

### ISSUE THREAD

**Issue by timvdsm** [JimStar/reolink_cctv#132]
**Describe the bug**
The Reolink Video Doorbell Siren is not working properly for the (PoE) doorbell. 
The state of the siren entity is not updated in HA when I activate it through the Reolink app, nor is the doorbell siren itself activated when I activate the entity it in HA.

**To Reproduce**
Activate the siren through the Reolink app. The status of the siren entity in HA is not updated.
Or activate the siren through HA, the siren is not activated on the doorbell itself.

**Expected behavior**
The state of the HA siren entity should follow the activation from the reolink app, and also from HA you should be able to activate the siren. 

**Debug log would be very helpful**

Logger: reolink_ip.api
Source: custom_components/reolink_cctv/switch.py:493 
Integration: Reolink IP NVR/camera (documentation, issues) 
First occurred: 11:49:51 (1 occurrences) 
Last logged: 11:49:51

Host 192.168.1.106:443: command "AudioAlarmPlay" error.

**Log file:**
[home-assistant.log](https://github.com/JimStar/reolink_cctv/files/10290426/home-assistant.log)

**Screenshots**
<img width="395" alt="Scherm­afbeelding 2022-12-22 om 21 46 23" src="https://user-images.githubusercontent.com/14946020/209223133-fdee277d-f75a-4517-b44a-4291b001809f.png">

**Environment:**
 - Home Assistant Blue - OS 2022.12.8
 - Reolink PoE Doorbell
 - Firmware Version v3.0.0.1459_22102808

**Additional context**
All other created entities (motion det, person detection, visitor, ... ) are working well.

**Comment by JimStar** [comment]
Please feel free to re-open this after attaching the full debug log, as shown in the issue-template.

**Comment by timvdsm** [comment]
Sorry I added the issue-template. 
Possible to re-open it?

**Comment by JimStar** [comment]
I was talking about attaching the **full debug log**, not the issue-template. The config lines for the proper debug-log are shown in the **issue-template**.  
The debug log file should start with HA restart, and you need to switch this siren-switch back and forth, so that this is reflected in the log...

**Comment by timvdsm** [comment]
Ok, I attached the log file.
Many thanks!

**Comment by JimStar** [comment]
Should be fixed in [0.1.10](https://github.com/JimStar/reolink_cctv/releases/tag/0.1.10).

**Comment by timvdsm** [comment]
Hi many thanks for your very fast support. Really appreciated!
For me the siren entity is not available anymore in HA.
<img width="374" alt="Scherm­afbeelding 2022-12-23 om 09 07 00" src="https://user-images.githubusercontent.com/14946020/209299664-b0dcc095-017f-42e3-852d-4a6c2d71bf08.png">

I've attached the log (restarted HA & activated 4 times the siren through the reolink app).
[home-assistant.log](https://github.com/JimStar/reolink_cctv/files/10293528/home-assistant.log)

**Comment by JimStar** [comment]
Should be finally fixed in the [0.1.11](https://github.com/JimStar/reolink_cctv/releases/tag/0.1.11).

**Comment by timvdsm** [comment]
Many thanks!! It's working. 
It's linked to the button in the reolink camera "Activate siren sounds when motion is detected". 

Do you have any idea if there is a possibility to manually activate the siren? You can do it in the app by pushing the siren icon. The siren will then be active for 4 seconds. 

![IMG_9131](https://user-images.githubusercontent.com/14946020/209328935-2891e778-4d65-41c4-a75d-d27e1f77e32c.jpeg)
I guess it's not possible to activate that through HA?

**Comment by JimStar** [comment]
If you can do this in camera's web UI - then you could track what command is sent to the camera when you press this button in the web UI. I described how to do this in [this post](https://github.com/JimStar/reolink_cctv/issues/118#issuecomment-1352044671) in other ticket...

**Comment by timvdsm** [comment]
Thanks for the proposal!
It seems the button is not available in the cameras web UI, only in the mobile and pc client. So I can't track the command. I suppose there is not tracking possible for the mobile/pc clients? 
And thanks again for your continuous support. Your reolink integration is working very well! And off course  ... Happy holidays!

**Comment by quizzical86** [comment]
@timvdsm  Please write to Reolink on their website or support@reolink.com to request that they enable this in their API.
It's part of the list of missing functionalities that I've listed here: https://community.home-assistant.io/t/homeassistant-and-reolink-doorbell-poe/485857/48?u=quizzical

**Comment by timvdsm** [comment]
@quizzical86 Hi I already send an email to reolink support. about this: 

> Is it possible from the camera web UI to:
> - Manually activate the siren of the PoE doorbell? In the app you trigger the doorbell siren by hitting the bell icon. However I can’t find it in the web UI of the camera.
> - Use Quick Reply messages

This is their response:

> Many thanks for your feedback on these features on the web UI.
> We will ask our developers to see if it's possible to add in the future firmware version.

**Comment by timvdsm** [comment]
I’ve asked if they could give me the commands  for:

This was their response:

> As for the Siren, please check the document in the attachment (http api user guide v7) and try the command for "SetAudioAlarmV20".
> 
> ![3E9A75AF-E3F9-4DAC-9076-FB14B5A82D42](https://user-images.githubusercontent.com/14946020/209918223-7dd773f9-e33e-4500-afce-d9fc710775d7.jpeg)
> 
> As for the quick reply, we will ask our engineers to update the commands in the next version.

Is this helpfull?

**Comment by JimStar** [comment]
Their API "guide" is just a joke. There is no proper description of commands in there. For example this "description" is just a long version of the words the command itself is consisting from. 😆

<img width="686" alt="Screen Shot 2022-12-29 at 20 44 26" src="https://user-images.githubusercontent.com/3421219/209920039-370c988e-1a09-44c3-9a48-061505d9f04e.png">

What I see (and could analyze from what I see) in the `GetAudioAlarmV20` parameters - it's just a command setting up a **schedule** for the alarm, not manually switching on/off the siren **right now**...

**Comment by JimStar** [comment]
... This is why I asked about debugging the command sent by them to the device - this is much more descriptive than their API "guide"...

**Comment by timvdsm** [comment]
I send en email back to Reolink to clarify :-) let's hope they can explain it a little bit better as normally they should know their own product ;-)

However I found another discussion on the same topic, it seems it's this command?
"AudioAlarmPlay"
Would that be more logical? 

For activating the siren manually:
alarm_mode: manu
manual_switch: 1

For desactivating the siren manually:
alarm_mode: manu
manual_switch: 0

For activation the siren for a timed perioed:
alarm_mode: times
manual_switch: 1
times: 3

I also found a document which explains the commands for all the reolink client menu setting. It's in French, but there are a lot of English screenshots and responding commands.
I guess you already have this information, so sorry to bother you with it. But you never know, it can be useful.
 
[DOC Reolink Correspondance Commandes-Menus_AI.pdf](https://github.com/JimStar/reolink_cctv/files/10322462/DOC.Reolink.Correspondance.Commandes-Menus_AI.pdf)

**Comment by JimStar** [comment]
The siren switch (using the `AudioAlarmPlay` command) has been available already in this integration.

**Comment by timvdsm** [comment]
Well that's strange, as I don't see it in HA.

**Comment by JimStar** [comment]
It will be created only if you have alarm enabled in your camera (`GetAudioAlarmV20` command must return `enable = 1`).

**Comment by timvdsm** [comment]
So the setting in the screenshot down under should be activated? And then I should reload the integration? Or fully re-install it? And then the entity will become available to manually activate the siren? 
Sorry for all these questions :-) 

<img width="850" alt="Scherm­afbeelding 2022-12-30 om 00 48 04" src="https://user-images.githubusercontent.com/14946020/210021883-00a11736-fb47-43fa-a1dc-ac2d1601e14d.png">

**Comment by JimStar** [comment]
Just restarting the HA will be enough. No need to re-install the integration.

**Comment by timvdsm** [comment]
That doesn’t seem to work.
I only have following entities available .. 
![1A52D60B-214F-4BB2-9E8E-29042623FE2C](https://user-images.githubusercontent.com/14946020/210070692-3f06d983-e40d-4dfc-bacb-6238276b10c2.jpeg)
![BDF8C4AF-5F0D-45EA-91DD-7A85311979A9](https://user-images.githubusercontent.com/14946020/210070698-d2411a34-fddf-4098-83d8-7c1e61db5e68.jpeg)

**Comment by JimStar** [comment]
<img width="827" alt="Screen Shot 2022-12-31 at 10 38 48" src="https://user-images.githubusercontent.com/3421219/210113382-cce755a6-77b1-4db7-8264-bc7b066463b2.png">

**Comment by timvdsm** [comment]
I'm really sorry to bother you and thanks again for your time and effort 😇 ... thats not the manual triggering of the siren, but the setting to activate the siren in case of motion detection. If you activate it, the next time there is motion, the siren will be triggered. 
That's this one from the webUI ... 
![](https://user-images.githubusercontent.com/14946020/210021883-00a11736-fb47-43fa-a1dc-ac2d1601e14d.png)
That's working after the changes you made earlier. 
I thought that was linked to `SetAudioAlarmV20`?

However, the manual triggering of the siren is something else and should be done with `AudioAlarmPlay`.
And that one was already integrated you mentioned. 
So then I suppose there should be 2 siren switches? Is that correct. 
However I just see 1.

**Comment by JimStar** [comment]
This siren switch does exactly what you said - it enables the siren by the `SetAudioAlarmV20` command, and immediately after that sends the `AudioAlarmPlay` command with `alarm_mode = manu` parameter.

If that doesn't work for you - this is exactly why I asked for the debug-tracing what Reolink app/web-ui sends to the device for that... Because their API guide is useless in this regard, and I don't have any siren-enabled cameras...

**Comment by timvdsm** [comment]
Unfortunately it's not possible to manually trigger the siren through their webUI. So I can't trace it myself.

However I just got a reply from Reolink:
If you would like to manually turn on or off the Siren, the command is `AudioAlarmPlay` and the alarm mode should be "manul". 
(*There's an "l" missing in the document we sent. Sorry for that).
Below is an example: 
![image](https://user-images.githubusercontent.com/14946020/210115707-37e348a5-dc7a-4d66-819a-81ea6768a55b.png)

![image](https://user-images.githubusercontent.com/14946020/210115720-c7db2f96-4760-4108-b86d-3c4fe89c6e6f.png)

So maybe there is just a typo (as their api documentation seems to be wrong) : `alarm_mode = manu` should be  `alarm_mode = manul`

**Comment by JimStar** [comment]
Yep, looks like one more screw-up in their "guide"..;)  
I'll change "manu" to "manul" in the next version.

**Comment by timvdsm** [comment]
Well their api documentation must be a real pain in the ass for you :-) 
Many thanks for the support! Appreciated 👏🏻👍🏻

**Comment by JimStar** [comment]
Should be fixed in [0.1.15](https://github.com/JimStar/reolink_cctv/releases/tag/0.1.15).

**Comment by timvdsm** [comment]
Hi many thanks for your support. We are almost there.
The command `alarm_mode: manul` is working.
However it seems there are 2 commands (`SetAudioAlarmV20`  & `AudioAlarmPlay` ) related to the same siren entity.
I think the 2 things are mixed together, but they need to be separated. As they are totally different.
Now the 2 commands are used for the same entity, which is not correct. 

- Setting of automatically trigger the siren when motion is detected
This is done with the command `SetAudioAlarmV20`
And this is just a setting.
The entity should be called "Siren when motion detected" or something like that :-)

- Manually trigger the siren when you want yourself
This is done with the command `AudioAlarmPlay`
The entity should be called "Siren" as it is now :-)

Manually trigger siren with `AudioAlarmPlay`: 
<img width="284" alt="Scherm­afbeelding 2023-01-01 om 10 23 52" src="https://user-images.githubusercontent.com/14946020/210166253-01c71ae2-bb78-4a49-92ca-69ad78f9abff.png">

Manually desactivate siren: 
<img width="250" alt="Scherm­afbeelding 2023-01-01 om 10 24 00" src="https://user-images.githubusercontent.com/14946020/210166259-9f87cd6b-f15f-4610-a78d-2c4f22e6df8c.png">

I am really sorry for my bad explanation. I hope you can understand it :-) 
Would it be possible to separate the 2 entities? 

Many thanks

**Comment by JimStar** [comment]
There is a problem with Reolink's API consistency that makes it not possible to use `AudioAlarmPlay` separately from `SetAudioAlarm` in a **toggle**-switch (a switch having a **state**) application.

But first of all, to ever start thinking about any workarounds of this, I need to know **what is your USE** of these made as *two separate-switches*. What problem you'd solve by having these as two separate switches, that couldn't be solved by this current one "siren" switch.

**Comment by timvdsm** [comment]
Hi, it seems I missed your reply. Sorry for that. 

> it not possible to use `AudioAlarmPlay` separately from `SetAudioAlarm` in a **toggle**-switch (a switch having a **state**) application
Oh OK, I didn't know that. It's def not logical as these are 2 separated functionalities and they are both activated when toggling the switch, but that's off course reolinks fault.

Well you def don't need to putt some time in a workaround :-). Your support is already much appreciated 👍🏻.
My use case is the following: I want to be able to manually activate the siren in case of an emergency. We can click the alarm button and all outside sirens will be activated. The doorbell siren covers the front side of the house. So that would be useful. 
But it seems that's it practically working with the implementation you've done now. Toggling the switch will activate both functions, so also the manual activation of the siren is working. So thanks for that. 

Question: Is it necessary to first activate the toggle switch when restarting HA? I thought you mentioned it somewhere... or is that from an implementation side not necessary?

**Comment by JimStar** [comment]
No, it is not necessary to activate the switch when restarting.
