### ISSUE TITLE
My HA Disk is getting full with .jpg files in config/.storage/reolink_cctv/

### ISSUE THREAD

**Issue by pablomarquesmendez** [JimStar/reolink_cctv#136]
**Describe the bug**
My HA Disk is getting full with .jpg files in config/.storage/reolink_cctv/

**To Reproduce**
Install reolink_cctv in HA

**Expected behavior**
My HA Disk is getting full with .jpg files in config/.storage/reolink_cctv/
Not sure what those jpg files are there for.
Is there away to limit the number of them for each camera?

**Debug log would be very helpful**
[core-ssh ~]$ find config/.storage/reolink_cctv/
config/.storage/reolink_cctv/
config/.storage/reolink_cctv/ec71dbbf5932
config/.storage/reolink_cctv/ec71dbbf5932/0
config/.storage/reolink_cctv/ec71dbbf5932/0/1671671566.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1671424504.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1671677819.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1671547840.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1671672240.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1671959655.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1671924114.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1672028486.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1671459085.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1671506120.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1671494160.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1671687518.0.jpg
config/.storage/reolink_cctv/ec71dbbf5932/0/1672058392.0.jpg
etc ...

**Environment:**
Please provide useful information about your environment, like:
Home Assistant 2022.12.7
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.1 - latest
Running on a Raspberry Pi4 4G Mem, 32G disk

**Comment by JimStar** [comment]
You just need to set up a periodic automation calling `cleanup_thumbnails` service.

**Comment by pablomarquesmendez** [comment]
Automation setup for daily cleanup.
Thank you.

**Comment by bikeymouse** [comment]
How would you need to call this service? 
If I call it like this, nothing seems to happen:

```
service: reolink_cctv.cleanup_thumbnails
data: {}
target:
  entity_id:
    - camera.reolink_doorbell_snapshots

```
Also tried this with all the other camera entities with no avail.

**Comment by JimStar** [comment]
This service will only remove snapshot files older than "playback range" setting of the entry config, leaving all the newer files there. It doesn't matter what camera type you select, it just takes the channel number of it and clears all the old image-files of that channel...

**Comment by bikeymouse** [comment]
Ah, yes, that's how it works. Thanks!
I now see this in the documentation as well, sorry for not reading properly.

**Comment by stanogustafik** [comment]
My backups also became huge - few GB... this is my solution:
First of all install "delete" integrration in home assistant - https://github.com/chomupashchuk/delete-file-home-assistant
and then:


alias: Delete Reolink after 7 days
description: Every night deletes files older than 7 days in Reolink folder
trigger:
  - platform: time
    at: "00:00:30"
condition: []
action:
  - service: delete.files_in_folder
    data:
      folder: /config/.storage/reolink_cctv
      scan_subfolders: true
      time: 604800
mode: single
