### ISSUE TITLE
Add AutoTrack stream for dual lens cameras like Reolink TrackMix

### ISSUE THREAD

**Issue by craigueh** [JimStar/reolink_cctv#143]
Hi Jim. 

First, thank you for your hard work on this integration. It has made my life so much easier since switching from the previous reolink_dev integration. 

I have recently purchased a Reolink TrackMix dual lens camera with auto tracking feature but the second camera stream with tracking doesn’t appear in Homeassistant. 

I’d like to use this stream to push to a display on my wall when a vehicle motion detection event occurs. 

Is it possible to add this stream to the integration? I’m not sure how tricky it would be without having one of the cameras to hand but I’m happy to test anything you need. 

Thanks.

**Comment by JimStar** [comment]
To start with - you need to attach here the **full** debug log, starting with HA restart. The config lines to enable debugging for this component are in the issue template.

**Comment by JimStar** [comment]
Feel free to reopen this after attaching the debug-log...
