### ISSUE TITLE
Lost FTP switch

### ISSUE THREAD

**Issue by Eddie46848** [JimStar/reolink_cctv#149]
**Describe the bug**
0.1.16 I have lost FTP switch on rlc410 , rlc510 is ok. Might have started in version 0.1.15

**Environment:**
Please provide useful information about your environment, like:
 - 2022.12.9
 -
 - 

**Additional context**
Went back to 0.1.14 and FTP switch is visible again.

**Comment by JimStar** [comment]
Please attach a full debug-log here.

**Comment by JimStar** [comment]
Try if it's fixed by [0.1.17](https://github.com/JimStar/reolink_cctv/releases/tag/0.1.17).

**Comment by Eddie46848** [comment]
Hi
Yes it's fixed now. Thanks for your help and hard work.
