### ISSUE TITLE
KeyError: Channel after latest update

### ISSUE THREAD

**Issue by vmonkey** [JimStar/reolink_cctv#150]
First, many thanks for the integration!

I have two rlc410-5mp cameras. After the latest integration update, my HA logs show 

Logger: reolink_ip.api
Source: custom_components/reolink_cctv/host.py:214
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 4. ledna 2023 22:08:54 (5264 occurrences)
Last logged: 09:08:39

Host 192.168.68.100:443 (channel 0) failed mapping JSON data: 'channel', traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 1572, in map_channel_json_response response_channel = data["value"]["Rec"]["schedule"]["channel"] KeyError: 'channel'
Host 192.168.68.108:443 (channel 0) failed mapping JSON data: 'channel', traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 1534, in map_channel_json_response response_channel = data["value"]["Email"]["schedule"]["channel"] KeyError: 'channel'
Host 192.168.68.108:443 (channel 0) failed mapping JSON data: 'channel', traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 1519, in map_channel_json_response response_channel = data["value"]["Push"]["schedule"]["channel"] KeyError: 'channel'
Host 192.168.68.108:443 (channel 0) failed mapping JSON data: 'channel', traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 1509, in map_channel_json_response response_channel = data["value"]["Ftp"]["schedule"]["channel"] KeyError: 'channel'
Host 192.168.68.108:443 (channel 0) failed mapping JSON data: 'channel', traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 1572, in map_channel_json_response response_channel = data["value"]["Rec"]["schedule"]["channel"] KeyError: 'channel'

**Comment by JimStar** [comment]
Please attach a full debug-log here.

**Comment by JimStar** [comment]
Try if it's fixed by [0.1.17](https://github.com/JimStar/reolink_cctv/releases/tag/0.1.17).

**Comment by vmonkey** [comment]
@JimStar Thanks, it seems to be fixed!
