### ISSUE TITLE
Reolink 511WA Not Showing Camera Entity

### ISSUE THREAD

**Issue by FancyNerd92** [JimStar/reolink_cctv#152]
Hello,
i have my Reolink 511WA and even it provides the switch. and binary. it don't provide camera. entirty at all. Any ideas?
I put ONVIF but it;'s not for me because i don't get a live video but it has see a delay on timestamp counts every 7sec-10sec.

**Comment by JimStar** [comment]
Sorry, but I cant comprehend this jibberish description... Plus you ignored a full debug-log file clearly asked in the issue template...

**Comment by FancyNerd92** [comment]
It's not jibberish, the Add-On not provides camera entity. What part of that is jibberish?
