### ISSUE TITLE
Request and not a Issue - Floodlight Reolink

### ISSUE THREAD

**Issue by MiAutomations** [JimStar/reolink_cctv#157]
Regarding the new devices floodlight from the Reolink 

Is there any chance to be supported in this integration?

I think this can me a usefully devices to integrate in the Home Assistant to create the automations with this devices and cameras 

Thank you and best regards

**Comment by JimStar** [comment]
This is already supported for cameras with white-LED feature, see the "spotlight" switch. I'm not sure if this new device supports the Reolink network API to use this same API-command on it - I don't have this device and I don't have any debug log from anybody owning it... But I suspect that if you already tried in with this plugin and it didn't work - then most likely the plugin was unable to get responses on API-calls from that device, that most likely means there is no network-API support in this device...
