### ISSUE TITLE
Push notification switch issue

### ISSUE THREAD

**Issue by tlamoureux24** [JimStar/reolink_cctv#158]
Hello,

First of all, i would like to thank you for this integration, the best for the reolink camera.
I just have only one issue with the push notification switch.
It simply do nothing !!!
If push notification is on with the reolink app, it remains on or off in home assistant and vice versa.
Changing the switch in home assistant do nothing in reolink app and vice versa.

I try putting the logger in debug, nothing in the file.
Same with activating debug in GUI with the three dots in integration.

Home Assistant : HAOS 9.4
Home Assistant Core : 2023.1.7
Supervisor : 2022.12.1

Reolink Camera : RLC-811A
Firmware: v3.1.0.989_22051908
Matériel : IPC_523128M8MP

Reolink Camera : RLC-823A
Firmware: v3.1.0.989_22051911_v1.0.0.30
Matériel : IPC_523128M8MP

I have no NVR.

Thanks.

**Comment by JimStar** [comment]
I need a full debug log, starting with HA restart, when you switching this switch back and forth...  
The config lines to enable it properly are in the issue template.

**Comment by tlamoureux24** [comment]
[home-assistant.log](https://github.com/JimStar/reolink_cctv/files/10493704/home-assistant.log)

Here the complete log file as you request.
Let me know if i can help you much.

Thank you.

**Comment by JimStar** [comment]
From you log file I see the plugin properly sends the push "enable" command to your device, and it responds with "OK". Could you describe a little more what you see in the camera's UI after that?..

**Comment by tlamoureux24** [comment]
I will try to explain better.
If push notification is disable on camera's ui, it's always enable in home assistant integration, even if i reload integration, same if i restart home assistant, same if i restart home assistant hardware and same if i restart the camera.
I try remove then re add camera, same.
If push notification is enable or disable in camera's ui, changing the switch in home assistant change nothing in camera's ui.
If push notification is enable or disable in home assistant, changing the switch in camera's ui change nothing in home assistant.

Today i have no time cause work but tomorrow i can make a video with smartphone and pc side by side and show you exactly what i mean.

**Comment by tlamoureux24** [comment]
Hello,

I investigate much more this bug today.
It appears that if i disable push notification with your integration, it works and push notification are really disable but in android app at least push notification still looks enable !!!!
So the state of the android button on the app doesn't change and it looks like the bug is in the android app.
I have tried all the button between android app and your integration, all works except the push nitification :(

So i'm sorry, it's not a bug of your integration but looks more a bug in the andoid app .......

Thanks for your time.
