### ISSUE TITLE
Visitor sensor missing

### ISSUE THREAD

**Issue by robertjan** [JimStar/reolink_cctv#159]
EDIT: issue solved, seems to be that there are 2 HACS intergrations and I used the wrong one

First of all thanks for all great job of this intergration!

I just received my POE doorbell and configured it with all the ports open and installed it with your configuration, i see 13 entity`s in total but it is missing the "visitor" sensor so i can`t create any automation based on the doorbell button.. can you please help me out?

firmware version: v3.0.0.1459_22102808
No NVR

**Comment by JimStar** [comment]
Please attach a full debug log as stated in the issue template.
