### ISSUE TITLE
Person and Vehicle detection not working in HA with a RLC-510WA

### ISSUE THREAD

**Issue by MassakerGU** [JimStar/reolink_cctv#163]
**Describe the bug**
Person and Vehicle detection not working in HA with a RLC-510WA. Only sometimes. It works in Synology Surveillance Station. 
Normal Motion Detection is turned off. 

**To Reproduce**
Use a RLC-510WA in HA. 

**Expected behavior**
binary_sensor should be switching to detected. In Synology Surveillance Station the Person/Vehicle Detection from the Camera works.

**Comment by JimStar** [comment]
Feel free to reopen this after attaching a **full debug log**, stated in the issue template...
