### ISSUE TITLE
Very slow integration startup time

### ISSUE THREAD

**Issue by smenzer** [JimStar/reolink_cctv#164]
**Describe the bug**
This integration takes an incredibly long time to start up when rebooting. I'm wondering if the timing I'm seeing is normal, potentially there's an opportunity for improvement in the code, or if there's something unique with my setup that is causing this.

**To Reproduce**
* Restart home assistant
* Navigate to Settings > System > Repairs > 3 dots menu > Integration Startup Time
* View the time for this integration

**Expected behavior**
I would expect a startup under 60 seconds like all other integrations

**Debug log would be very helpful**
[home-assistant_2023-01-31T04-05-14.977Z_reolink-only.log](https://github.com/JimStar/reolink_cctv/files/10542646/home-assistant_2023-01-31T04-05-14.977Z_reolink-only.log)

**Screenshots**
Restart # 1:
<img width="449" src="https://user-images.githubusercontent.com/624392/215659310-64268e9f-cf98-4170-9309-2ac30e418186.png">

Restart # 2 (logs are from this startup):
<img width="449" alt="image" src="https://user-images.githubusercontent.com/624392/215660958-5881d09f-a923-43a6-ba1c-382828af06d4.png">

**Environment:**
- 6 cameras integrated directly and set up as separate integrations, most are E1 Zoom with firmware v3.0.0.1107_22070508
- Home Assistant 2023.1.5
- Supervisor 2023.01.1
- Operating System 9.4

**Comment by JimStar** [comment]
Looks like nothing to do with this component. Something is terribly wrong with your HA setup... It takes just over a second on my side:

<img width="472" alt="Screen Shot 2023-01-31 at 17 16 45" src="https://user-images.githubusercontent.com/3421219/215663300-fc313720-1864-4549-81b6-91435a980923.png">

And in your log I see the initialization and login to all your cameras took just over a second too... But I see there are some HA internal Reolink integration is trying to initialize itself too in your log - maybe you have them **both** enabled and they could be conflicting...

**Comment by smenzer** [comment]
Thanks for taking a look. I do have the standard reolink integration setup because I can't access my e1 pro through this integration since it doesn't support the api yet. I'll try disabling that and see if it speeds things up.
