### ISSUE TITLE
Should I migrate to the official integration?

### ISSUE THREAD

**Issue by markaggar** [JimStar/reolink_cctv#171]
Hi, wanted to get your thoughts on migrating to the official HA reolink integration built by StarkillerOG (which I'm wondering might also be you??).

Also, there's a reference in the HA docs for the reoli k integration about beta firmware which addresses the motion detection push notification issue.  I've installed what appears to be a later release of firmware (3.2.xxx) for the 26 channel NVR, but not seeing any difference, so not sure if the firmware doesn't have the fix or there's still a bug in this integration.

Tx!

**Comment by JimStar** [comment]
The HA "official" integration is based on this one. I already explained few times, you can just read more in this post and the one linked in it: https://github.com/JimStar/reolink_cctv/issues/153#issuecomment-1396675846.

Regarding new beta firmware from Reolink: I tried it few days ago after they sent it to me, and it appeared to be so glitchy, that even Reolink Mac and Android applications stopped working with the "upgraded" NVR. Not to mention this component stopped even loading with it - which means they changed something significant in their network-API but did not let me know about it when sent me their beta firmware.  
I don't want to leave my house vulnerable with this glitchy firmware, so I flashed back their latest **stable** firmware, and will be waiting before they release a **properly tested** firmware that at least works OK with their own applications on Mac and Android... No sense for me to change this component to make it work with their changed API before they make the new firmware **usable**...

**Comment by markaggar** [comment]
Thanks Jim.  Glad to see you are continuing to maintain it.  There's new 3.2.x Firmware as of Feb 9th where they optimized network settings amongst other things.  I noticed that Onvif got turned off in my NVR, and now requires rtsp to be turned on to enable it.  I enabled it and reloaded the integration, but didn't seem to make a difference. The beta firmware was 3.0.x, so it seems like this is later.  Haven't had any stability issues with it on my 16 channel NVR.

Tx!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
