### ISSUE TITLE
Service camera.screenshot will take a high res picture from sub/ext stream

### ISSUE THREAD

**Issue by klickfisch** [JimStar/reolink_cctv#176]
I use the "service: camera.snapshot" to generate an image which will send to my mobile phone if anyone rings at my frontdoor.
The substream is configured with 640x480@128kbps.
If i run the service it will generate a 2560x1920 pixel image from that stream - how is that possible? I only want a 640x480 pixel image to save data (and time) while sending it to my phone.

This will also happen with the "official" Reolink integration, but not with the ONVIF integration

Cameras tested:
Video Doorbell PoE
RLC-520
RLC-420

Version: 0.1.18

**Comment by JimStar** [comment]
Sorry, but there is no size attributes in Reolink's snapshot API. It doesn't take a snapshot "from a stream", it just requests a snapshot of a channel by the Reolink's `Snap` command. It's from their API guide:

<img width="516" alt="Screen Shot 2023-03-09 at 20 16 25" src="https://user-images.githubusercontent.com/3421219/223948891-dfda3ae2-0425-45d9-b064-2d8db9505486.png">

**Comment by klickfisch** [comment]
Ok thanks for that. I also read, that i can add a eg "...&width=640&height=480" to the end of the command. Is it possible to integrate that?

**Comment by JimStar** [comment]
Did you try this yourself? Does it work?  
It's not mentioned in Reolink API guide...

**Comment by klickfisch** [comment]
Found it in their help section: https://support.reolink.com/hc/en-us/articles/360007011233-How-to-Capture-Live-JPEG-Image-of-Reolink-Cameras-via-Web-Browsers

**Comment by JimStar** [comment]
OK, looks like an undocumented feature. When I have time I'll have a look if we could have it in this component...
