### ISSUE TITLE
Visitor sensor not updating after a while untill reloading integration

### ISSUE THREAD

**Issue by sanderlv** [JimStar/reolink_cctv#179]
**Describe the bug**
Everything works fine. Until after a while (hours) the doorbell visitor sensor does not report bell presses anymore.

If the integration is reloaded all is fine again, until it stops...

**To Reproduce**
I do not know how to reproduce

**Expected behavior**
Sensor is updated correclty

**Debug log would be very helpful**
No debug is able to be captured

If applicable, switch on debug-logging, and attach here a full log-file: from the HA restart, and covering the time where the issue happened.  
```
logger:
  default: warning
  logs:
    custom_components.reolink_cctv: debug
    reolink_ip: debug
```

**Screenshots**
![image](https://user-images.githubusercontent.com/16528916/227533261-5ce27861-0dce-4ef4-b674-973cb02821eb.png)

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version: 
 
![image](https://user-images.githubusercontent.com/16528916/227533502-4a2f0cbb-481c-441b-8a0c-7a9da438fd6e.png)

 - Reolink NVR/camera model
 
doorbell PoE

 - NVR/camera firmware
![image](https://user-images.githubusercontent.com/16528916/227533751-0cba7f40-aee6-49c7-a7e3-0c327a8135fb.png)

**Additional context**
Maybe any other context about the problem here.

**Comment by FerronN** [comment]
I've the same problem.

**Comment by FerronN** [comment]
I've managed to get a dump of what is send (ONVIF notifications).
For me it looks like the notification is send correctly, but in HA the `Visitor` sensor stays off.

```
POST /api/webhook/reolink_Deurbel_webhook HTTP/1.1
Host: <my.domain.fake>
User-Agent: gSOAP/2.8
Content-Type: application/soap+xml; charset=utf-8; action="http://docs.oasis-open.org/wsn/bw-2/NotificationConsumer/Notify"
Content-Length: 5398
Connection: close
SOAPAction: "http://docs.oasis-open.org/wsn/bw-2/NotificationConsumer/Notify"


<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope
	xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope"
	xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
	xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery"
	xmlns:xop="http://www.w3.org/2004/08/xop/include"
	xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex"
	xmlns:wsa5="http://www.w3.org/2005/08/addressing"
	xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#"
	xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
	xmlns:saml1="urn:oasis:names:tc:SAML:1.0:assertion"
	xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"
	xmlns:wsc="http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512"
	xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
	xmlns:tt="http://www.onvif.org/ver10/schema"
	xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2"
	xmlns:wstop="http://docs.oasis-open.org/wsn/t-1"
	xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2"
	xmlns:ns1="http://www.onvif.org/ver20/media/wsdl"
	xmlns:tdn="http://www.onvif.org/ver10/network/wsdl"
	xmlns:tds="http://www.onvif.org/ver10/device/wsdl"
	xmlns:tev="http://www.onvif.org/ver10/events/wsdl"
	xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2"
	xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl"
	xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl"
	xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl"
	xmlns:trc="http://www.onvif.org/ver10/recording/wsdl"
	xmlns:trp="http://www.onvif.org/ver10/replay/wsdl"
	xmlns:trt="http://www.onvif.org/ver10/media/wsdl"
	xmlns:trv="http://www.onvif.org/ver10/receiver/wsdl"
	xmlns:tse="http://www.onvif.org/ver10/search/wsdl"
	xmlns:ter="http://www.onvif.org/ver10/error"
	xmlns:tns1="http://www.onvif.org/ver10/topics"
	xmlns:tad="http://www.onvif.org/ver20/analytics/wsdl">
	<SOAP-ENV:Header>
		<wsa5:Action SOAP-ENV:mustUnderstand="1">http://docs.oasis-open.org/wsn/bw-2/NotificationConsumer/Notify</wsa5:Action>
	</SOAP-ENV:Header>
	<SOAP-ENV:Body>
		<wsnt:Notify>
			<wsnt:NotificationMessage>
				<wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:RuleEngine/CellMotionDetector/Motion</wsnt:Topic>
				<wsnt:Message>
					<tt:Message UtcTime="2023-03-25T10:55:13Z" PropertyOperation="Changed">
						<tt:Source>
							<tt:SimpleItem Name="VideoSourceConfigurationToken" Value="000" />
						</tt:Source>
						<tt:Data>
							<tt:SimpleItem Name="IsMotion" Value="false" />
						</tt:Data>
					</tt:Message>
				</wsnt:Message>
			</wsnt:NotificationMessage>
			<wsnt:NotificationMessage>
				<wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:RuleEngine/MyRuleDetector/FaceDetect</wsnt:Topic>
				<wsnt:Message>
					<tt:Message UtcTime="1970-01-01T00:00:00Z" PropertyOperation="Initialized">
						<tt:Source>
							<tt:SimpleItem Name="Source" Value="VideoSourceToken" />
						</tt:Source>
						<tt:Data>
							<tt:SimpleItem Name="State" Value="false" />
						</tt:Data>
					</tt:Message>
				</wsnt:Message>
			</wsnt:NotificationMessage>
			<wsnt:NotificationMessage>
				<wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:RuleEngine/MyRuleDetector/PeopleDetect</wsnt:Topic>
				<wsnt:Message>
					<tt:Message UtcTime="2023-03-25T11:12:54Z" PropertyOperation="Changed">
						<tt:Source>
							<tt:SimpleItem Name="Source" Value="VideoSourceToken" />
						</tt:Source>
						<tt:Data>
							<tt:SimpleItem Name="State" Value="false" />
						</tt:Data>
					</tt:Message>
				</wsnt:Message>
			</wsnt:NotificationMessage>
			<wsnt:NotificationMessage>
				<wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:RuleEngine/MyRuleDetector/VehicleDetect</wsnt:Topic>
				<wsnt:Message>
					<tt:Message UtcTime="1970-01-01T00:00:00Z" PropertyOperation="Initialized">
						<tt:Source>
							<tt:SimpleItem Name="Source" Value="VideoSourceToken" />
						</tt:Source>
						<tt:Data>
							<tt:SimpleItem Name="State" Value="false" />
						</tt:Data>
					</tt:Message>
				</wsnt:Message>
			</wsnt:NotificationMessage>
			<wsnt:NotificationMessage>
				<wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:RuleEngine/MyRuleDetector/DogCatDetect</wsnt:Topic>
				<wsnt:Message>
					<tt:Message UtcTime="1970-01-01T00:00:00Z" PropertyOperation="Initialized">
						<tt:Source>
							<tt:SimpleItem Name="Source" Value="VideoSourceToken" />
						</tt:Source>
						<tt:Data>
							<tt:SimpleItem Name="State" Value="false" />
						</tt:Data>
					</tt:Message>
				</wsnt:Message>
			</wsnt:NotificationMessage>
			<wsnt:NotificationMessage>
				<wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:VideoSource/MotionAlarm</wsnt:Topic>
				<wsnt:Message>
					<tt:Message UtcTime="2023-03-25T10:55:13Z" PropertyOperation="Changed">
						<tt:Source>
							<tt:SimpleItem Name="Source" Value="000" />
						</tt:Source>
						<tt:Data>
							<tt:SimpleItem Name="State" Value="false" />
						</tt:Data>
					</tt:Message>
				</wsnt:Message>
			</wsnt:NotificationMessage>
			<wsnt:NotificationMessage>
				<wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:RuleEngine/MyRuleDetector/Visitor</wsnt:Topic>
				<wsnt:Message>
					<tt:Message UtcTime="2023-03-25T11:12:57Z" PropertyOperation="Changed">
						<tt:Source>
							<tt:SimpleItem Name="Source" Value="000" />
						</tt:Source>
						<tt:Data>
							<tt:SimpleItem Name="State" Value="true" />
						</tt:Data>
					</tt:Message>
				</wsnt:Message>
			</wsnt:NotificationMessage>
		</wsnt:Notify>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>


```

**Comment by FerronN** [comment]
I've compared my package dumps with the logs in HASS. It looks to me that if the camera sends multiple webhooks within a few second the integration only proccesses the last one. Within my package dump I saw 4 webhook within 4 second and in the integration logs I only saw one incoming webhook.

**Comment by sanderlv** [comment]
I really hope this is going to be solved... at the moment it is not reliable at all when the signal is not correctly detected by HA and thus not correctly sent to my legacy doorbell. Thank you very much!

**Comment by JimStar** [comment]
Sorry guys for a delay, some busy with my main work right now. I'll check this out as soon as I have time for that...

For now you can check the "motion sensor off delay" setting in this component's config (maybe try to set it to 0) - maybe it's somehow related to this issue...

**Comment by FerronN** [comment]
I will test this👍

**Comment by FerronN** [comment]
With delay on 0 it works. But doesn't HA requests the doorbell status every second then? So we don't now if this setting is the problem for the webhooks?

**Comment by JimStar** [comment]
No, it doesn't poll anything, it is the same efficient with the setting set to "0".  
The purpose of this setting is to make the sensors to show triggering for **longer** time even if the trigger duration was like 0.1s and was not noticeable by a human eye... It is not needed for the computer automation.

**Comment by FerronN** [comment]
Ah okay, thank your for explaining. With the setting set to 0 the visitor sensor was on for 20 seconds. That's fine I think. Person detection was on for 6 second. Maybe an exclude visitor sensor option for this delay functionality?

**Comment by FerronN** [comment]
This morning the doorbell was pressed, but the visitor sensor did not update. The delay setting is still 0 :( The motion sensor was also not updated correctly. It went from on to OFF after a minute or so when the doorbell was pressed. After being on for 2,5 hours (that's not correct). So some webhooks are still not processed I think. 

If I can test something or if you need more info, please let me know.

**Comment by sanderlv** [comment]
I am going to put a sticker on the reolink.

"Do not use this, it's unreliable"

Then I get the signal via HA and telegram and I can start talking via the app if I need to.

It's a pity this is so unreliable...

(No offense to the writer of this integration, respect!)

**Comment by FerronN** [comment]
I debugged with postman to see if I could manually repeat the issue and I Coud. After looking at the source code I decided to set watch dog timer to 1 instead of 0. For now it seems to day, but I will report in a few days if it keeps working.

**Comment by JimStar** [comment]
The proper way to see what's happening - is to create a debug log with log-settings suggested in the issue-template. Then wait before this issue starts happening, and write down the exact time of that (to be able to find that time-point in the log).

I just don't have a doorbell-camera, so can't test it on my rig...

**Comment by FerronN** [comment]
I use my firewall to get package dumps. Then I compare them to the logs (debug mode). It still look like my firewall logs more request then that HA shows in the logs. Sometimes 3 requests can happen within a second. This seems to be problematic.

**Comment by starkillerOG** [comment]
Could be related to the webhook async task beeing cancelled when the camera closes the connection.
Solution is to shield the `handle_webhook` callback, see https://github.com/home-assistant/core/pull/89798

You can also try updating the doorbell firmware to v3.0.0.1859 (released 2 days ago).

@FerronN have you tried HA 2023.4 beta with the official integration?
That has the shield solution.

**Comment by sanderlv** [comment]
For me no update available in app. (PoE) currently running v3.0.0.1459_22102808

**Comment by starkillerOG** [comment]
@sanderlv you have to manually update and download firmware from https://reolink.com/download-center/, "online update" of reolink is verry buggy

**Comment by starkillerOG** [comment]
JimStar is maintaining this library, so maybe he could look at it.

HA 2023.4 supports all feature this library does except for the media browser to playback video.
It also supports some additional entities, like quick reply and volume control.
@sanderlv if you still experiance issues, I would advice to try out the build in integration in HA 2023.4

**Comment by FerronN** [comment]
@starkillerOG If I'm correct 2023.4 is releases tomorrow. So I'm gonna test it then ;) I've upgraded the Reolink just now. Thank for the heads up!

**Comment by sanderlv** [comment]
Thanks JimStar, should I see an HACS update?

**Comment by FerronN** [comment]
@starkillerOG I tried the bèta 2023.4 version, but it only show 7 entities and not the functionality you described. Am I missing something?

**Comment by starkillerOG** [comment]
@FerronN you will have to remove the custom reolink integration and setup the build-in reolink integration to get the additional entities.

**Comment by FerronN** [comment]
@starkillerOG That doesn't make a difference. Removing the device, restart HA and add the doorbell again, doesn't change anything either.

I removed the custom integration like you said. Any ideas?

**Comment by starkillerOG** [comment]
@FerronN are you sure you are already on HomeAssistant 2023.4 and are using the build-in integration?
You could try updating the doorbell firmware to v3.0.0.1859

**Comment by FerronN** [comment]
@starkillerOG lol, I updated the image tag and applied the configuration in k8s, but a new pod was not deployed... Now I'm on version 2023.4 and the first impression is good👍
