### ISSUE TITLE
Host 192.168.1.97:80: error translating host-settings response: Extra data: line 1 column 3 (char 2)

### ISSUE THREAD

**Issue by tempus2016** [JimStar/reolink_cctv#18]
**Describe the bug**

**To Reproduce**
Restart HA

**Expected behavior**

**Debug log would be very helpful**
If applicable, switch on debug-logging, and attach here a full log-file: from the HA restart, and covering the time where the issue happened.  
```
logger:
This error originated from a custom integration.

Logger: reolink_ip.api
Source: custom_components/reolink_cctv/host.py:167
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 21:51:36 (1 occurrences)
Last logged: 21:51:36

Host 192.168.1.97:80: error translating host-settings response: Extra data: line 1 column 3 (char 2)
```

**Screenshots**

**Environment:**
Please provide useful information about your environment, like:
Home Assistant 2022.10.1
Supervisor 2022.09.1
Operating System 9.0
Frontend 20221006.0 - latest

RLN8-410
Firmware: v3.0.0.173_22041117
822 4K Cameras

**Additional context**
Maybe any other context about the problem here.

**Comment by JimStar** [comment]
Would it be possible to attach here a full debug-log file (from the beginning of HA restart)?  
It's something specific in your camera response, I just need to see what it is, to make the component to support this...

**Comment by tempus2016** [comment]
What exactly do you need added to config to record what you need? I've never created a full debug log.  Is it just logger: thats needed?

**Comment by JimStar** [comment]
It was in the ticket-template.;)  
You just need this in your HA configuration:  
```
logger:
  default: warning
  logs:
    custom_components.reolink_cctv: debug
    reolink_ip: debug
```
You can just let it be there even when you don't need a debug-log, just replace the "debug" by "warning"...

**Comment by etamtlosz** [comment]
I have a similar error.
Somehow I can not download the logs anymore, there's no such option in the integration, or I'm doing something wrong.

**Comment by JimStar** [comment]
Should be in `/config/home-assistant.log`... Or you could just copy-paste from HA logger UI...

This error actually shows that Reolink firmware sends some malformed JSON response... So I definitely need the debug-log to see what it is.

But the interesting thing here - I have **the same** NVR model as @tempus2016, but I've never got any such issues. Which could mean that maybe something wrong with some particular Reolink's firmware version (I have the latest one)... I see @tempus2016 has **3.0.0.173**, but the latest one on Reolink download-section is **3.0.0.200**. So maybe makes sense to update your firmware first...

**Comment by etamtlosz** [comment]
Just restarted my HA (again) and the error is gone.
I'm going to keep an eye on it, in case it's going to reappear.

**Comment by JimStar** [comment]
Debug-log required

**Comment by tempus2016** [comment]
Sorry for the delay. There wasn't an error for a while.  I thought there would be a log created only for this integration but I don't see it. 

Before I post a log, is there anything in the file I should remove?  Webhooks etc?

**Comment by tempus2016** [comment]
https://pastebin.com/bE2XF734

**Comment by JimStar** [comment]
I don't see any records in your log with the error you've mentioned here...

**Comment by tempus2016** [comment]
Forgot to say, I haven't had that error again since posting about it.  I have had others but not got a log.  Will post when they appear

**Comment by JimStar** [comment]
OK, what I see in the log just posted by @etamtlosz:  
In response to a command, instead of a proper JSON response, the NVR just sent some jibberish-abracadabra garbage:

`U1auCoXnjehnaQz6/pTuA8Ak3PQBcIt1f1FvUfHlGey2bAXGmauWr69gssjy5StHkzXDhRCG2kxtu3DyldrG1bmSx+uAsRB8IZQjJuzT9ldwCo4QNIgIhXv4FwShWQzuwPc0DzZH0r0SEtFiX321Y//+91MR7PXtxBc4ECEbhAFNJ1J4ds1qPWr8dGwUhd18tpfvvoQ=`

Definitely some Reolink firmware bug.  
But the component should still work, it will just retry to request this data in the next iteration...

BTW, I have RLN8-410 too (with four RLC-822A), but never seen this error so far...

**Comment by JimStar** [comment]
I'll try to make some changes to the sessions' handling in the next version, maybe some chances to eliminate this...

**Comment by etamtlosz** [comment]
Sounds good. Thanks!

**Comment by JimStar** [comment]
**0.0.15** is now released.  
Most likely it will not fix, but it has some improvements in session handling, so maybe some chance it gets better...
