### ISSUE TITLE
sensors do not update

### ISSUE THREAD

**Issue by elchitico** [JimStar/reolink_cctv#183]
sensors do not update after updating to the latest version 0.1.19, if reloaded the integration starts working, but after a while all sensors stop updating again, when going back to the old version of the integration 0.1.18 everything works correctly again
![IMG_0886](https://user-images.githubusercontent.com/66695722/230797917-95221aee-5d4c-4260-9188-711e058ae281.png)

 sorry for my bad english my language is spanish

integration version: 0.1.19
Versión Home Assistant: 2023.4.1
failing devices: Reolink ring dórenlo
Firmware: v3.0.0.1459_22102806

**Comment by JimStar** [comment]
Please attach a debug log file, as described in the ticket template.

**Comment by elchitico** [comment]
Thanks for your attention. I suppose I have to remove the current version 0.1.18 and put 0.1.19, right?

**Comment by JimStar** [comment]
Yes. And the debug-log only makes sense if you wait before your issue starts happening. After that just attach here the **full** log file (starting with HA restart records).

**Comment by JimStar** [comment]
Feel free to reopen this after attaching the debug-file.
