### ISSUE TITLE
Doorbell entities not unavailable

### ISSUE THREAD

**Issue by ams3401** [JimStar/reolink_cctv#186]
**Describe the bug**
Following entities are not available:
- binary_sensor.doorbell_motion
- binary_sensor.doorbell_person_detected
- binary_sensor.doorbell_visitor

**To Reproduce**
- Install the integration via HACS, insert NVR's local IP address HTTP (port 80)
- Doesn't work when configured as HTTPS (port 443) either
- Made sure both ports are open both in the router and the NVR's setting

**Debug log would be very helpful**
https://gist.github.com/ams3401/ed5ebe5ec9f3772c3c1173d14e343ccc
I hope this is the correct way to reference debugging log.. please correct me if I'm wrong 

**Screenshots**
<img width="1053" alt="Screenshot 2023-04-24 at 3 32 24 PM" src="https://user-images.githubusercontent.com/70864968/234121633-18204bde-077d-465f-9713-d85008451323.png">

**Environment:**
 - Home Assistant version: 2023.4.6
 - Reolink NVR/camera model: Reolink Doorbell WIFI
 - NVR/camera firmware: DB_566128M5MP_W.2017_23041200.Reolink-Video-Doorbell-WiFi.OV05A10.5MP.WIFI8812.REOLINK.pak

**Comment by JimStar** [comment]
This is some issue in your network or NVR/camera network setup. From your log:

`2023-04-24 15:27:43.820 ERROR (MainThread) [reolink_ip.api] Host 192.168.1.19:443: connection error: Cannot connect to host 192.168.1.19:8000 ssl:default [Connect call failed ('192.168.1.19', 8000)].`

**Comment by ams3401** [comment]
> This is some issue in your network or NVR/camera network setup. From your log:
> 
> `2023-04-24 15:27:43.820 ERROR (MainThread) [reolink_ip.api] Host 192.168.1.19:443: connection error: Cannot connect to host 192.168.1.19:8000 ssl:default [Connect call failed ('192.168.1.19', 8000)].`

All necessary ports are open on the router as well as on the NVR setting. Could you maybe suggest any ideas of what could be the issue?
