### ISSUE TITLE
VLAN's, webhooks and internal URL

### ISSUE THREAD

**Issue by Markus9955** [JimStar/reolink_cctv#188]
My Home Assistant sits on a number of VLANs and the internal URL that is usually used is 192.168.**1**.201:8123.

I would like to have my Reolink cameras on a different VLAN from which you would need to access Home Assistant via 192.168.**3**.201:8123

However when connected in this configuration the webhooks fail as the URL passed to the camera is the 192.168.**1**.201:8123 address which it can't access. 

I did a quick trial with hardcoding the 192.168.**3**.201:8123 address on line 415 of host.py which got things up and running for me but I know is extremely dirty.

Is their a "proper" way to do this within Home Assistant settings or this integration? If not would you consider adding it as a configuration option?

**Comment by JimStar** [comment]
This is unrelated to the component.
