### ISSUE TITLE
Push Notification switch doesn't work with some camera

### ISSUE THREAD

**Issue by mattlemercier** [JimStar/reolink_cctv#198]
With one of my 2 Reolink IP cameras (RLC-1212A), the HA switch linked to the Push notifications doesn't work.
Both devices are on the same network, on the same router.

The entity is created in HA (switch.living_camera_push_notifications), but nothing happens when I turn it ON or OFF.
It doesn't activate or deactivate the push notification.
Toggling Push notification from the Reolink app in my smartphone works, but it doesn't affect the state of the Switch in HA. 

The "switch.doorbell_push_notifications" works fine for my other Camera.
All other switches created by the integration works fine for both cameras.
I see no error in the HA logs.

**Environment:**
 - Home Assistant version:
Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

 - Reolink NVR/camera model: RLC-1212A
 
 - NVR/camera firmware: v3.1.0.2174_23050815

![IMG_3976](https://github.com/JimStar/reolink_cctv/assets/101415754/4ee08752-23a8-4a78-99f5-cc76ed35b080)

**Comment by JimStar** [comment]
Please attach a debug log (as described in the issue template), where you're pressing this button for the problematic camera.

**Comment by mattlemercier** [comment]
Hi JimStar,
Here is more details.


1) First I checked that both of my Reolink cameras has the same configuration (as the issue only occures on one of them). It is the case. (Pic 1.jpg)

-----------------------------------------------------------
Changes in Reolink App doesn't impact the HA entitiy
-----------------------------------------------------------
2) From HA > Setting > Entities, I click on "switch.living_camera_push_notifications". The card opens with the status "ON".
   Whereas the push notification are actually disabled, as displayed in the Reoling app on my phone. (And I confirm that I don't 
   get push notifications). (Pic2.jpg)
   The state is "ON" as well in the HA > Developer Tools > States. (Pic3.jpg)
   
3) Then I turn the push notification "ON" from the Reolink app, and I directly get push notification (motion detected, as I'm in the field of the camera). (The state of the switch in HA didn't changed and remain "ON"). (Pic4.jpg)

4) Then I turn the push notifications "OFF" again from the Reolink app, and refreshed the browser. I do not get push notification any more. I check the switch in HA > Setting > Entitie, and "switch.living_camera_push_notifications" remained "ON". (Pic5.jpg).

5) After setting the "switch.living_camera_push_notifications" manually on state "OFF", I replayed step 1, 2, 3 , 4. And I observe the same behavior: the switch status never changes.

---------------------------------------------------------------------
Changes of HA entitiy doesn't impact the status in Relonk App
---------------------------------------------------------------------
6) When push notification are "OFF" in the app, toggling the switch ("switch.living_camera_push_notifications") "ON" in the entity card in HA, has no effect in the Reolink app. Event after exiting and entering back the app.

7) When push notification are "ON" in the app, toggling the switch ("switch.living_camera_push_notifications") "OFF" in the entity card in HA, has no effect in the Reolink app. Event after exiting and entering back the app.



![pic 1](https://github.com/JimStar/reolink_cctv/assets/101415754/96903714-c6ce-491c-83ef-152c39439cee)
![pic 2](https://github.com/JimStar/reolink_cctv/assets/101415754/996dcc6f-1b98-4f6f-8037-66769028ed07)
![pic 3](https://github.com/JimStar/reolink_cctv/assets/101415754/47926591-a57c-423e-bed6-731ef0d6dd55)
![pic 4](https://github.com/JimStar/reolink_cctv/assets/101415754/ba995938-7aa5-4930-b4d8-c718adcf4be6)
![pic 5](https://github.com/JimStar/reolink_cctv/assets/101415754/5a3129cc-4e5f-4db0-824f-31ed7f199034)

**Comment by JimStar** [comment]
No debug log provided as requested.

**Comment by mattlemercier** [comment]
Sorry, I forgot it.
Here they are.

[home-assistant_reolink_2023-07-31T07-02-56.397Z.log](https://github.com/JimStar/reolink_cctv/files/12212301/home-assistant_reolink_2023-07-31T07-02-56.397Z.log)

**Comment by JimStar** [comment]
https://github.com/JimStar/reolink_cctv/discussions/201
