### ISSUE TITLE
Timeout fetching reolink.REOLINK NVR data

### ISSUE THREAD

**Issue by Electronlibre2012** [JimStar/reolink_cctv#2]
**Describe the bug**
Logger: custom_components.reolink_cctv
Source: helpers/update_coordinator.py:151
Integration: Reolink IP NVR/camera ([documentation](https://github.com/JimStar/reolink_cctv), [issues](https://github.com/JimStar/reolink_cctv/issues))
First occurred: 10:40:47 (1 occurrences)
Last logged: 10:40:47

Timeout fetching reolink.REOLINK NVR data
**To Reproduce**
Steps to reproduce the behavior. Please provide the error from the log if possible.

**Expected behavior**
just error log events 
**Screenshots**

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version 2022.9.7
 - Reolink NVR/camera model N3MB01
 - NVR/camera firmware v3.0.0.173_22041117

**Additional context**
sorry perhaps my fault i have select rtsp instead of rtmp default...now seems to have no more error...i wait a few hours

awesome job you have made!!! no more errors about reolink subscription...motions sensors unavailable!!!!!!! awesome! thanks

**Comment by JimStar** [comment]
I'll be watching for this log record... Never got it on my side though, maybe just your NVR did not respond for some time right after HA restarted...

**Comment by JimStar** [comment]
I look at the place in the code, where it could happen, and I see it only happens if you have many cameras and not enough of timeout set up to request/receive all the status-data for every one of them.  
So the solution would be to just raise the connection-timeout value in the integration-config, and you should not see such messages again.

Please feel free to re-open this ticket if the above solution doesn't help and you still would see these messages sometimes...

**Comment by JimStar** [comment]
I've just released the version **0.0.2** where the default connection-timeout is increased, for cases with an NVR having a lot of cameras.

No need to update for you though just for that - you can just increase this timeout manually in the integration-config...

**Comment by Electronlibre2012** [comment]
thanks @JimStar!

**Comment by JimStar** [comment]
Just FYI:  
I've found one more reason the "unavailable" states could still sometimes happen. So if you experienced any of that with this new component - it should be improved in the **0.0.3** version I've just released...

**Comment by Electronlibre2012** [comment]
hello,

i have more error about complaining about http access denied with port 443. I first use the https adress of my NVR with SSL enable and notice some error with access denied on http with port 443 what should be of course https not http.

Perhaps there is something wrong in the code?

i delete the integration and install again after a restart of HA with http adress and port 8091, errors are gone.

i usually do integration with https but doesnt matter if it work on http, not a big deal.

Have a nice day.

**Comment by JimStar** [comment]
I'll investigate this...
