### ISSUE TITLE
There is no icon on the dashboard

### ISSUE THREAD

**Issue by garry0garry** [JimStar/reolink_cctv#23]
Home Assistant 2022.10.4, Frontend 20221010.0, HACS 1.28.0, Reolink IP NVR/cameras 0.0.12

Cleared browser cache. There is no icon on the dashboard.
![изображение](https://user-images.githubusercontent.com/95581374/195995308-9447de6c-ed0e-4092-8773-76da75422bf1.png)

**Comment by JimStar** [comment]
Please read the README file of the component.
