### ISSUE TITLE
Unavailable every hour

### ISSUE THREAD

**Issue by leroyloren** [JimStar/reolink_cctv#5]
**Describe the bug**
First of all, many thanks for improving the integration, now the log is clean of errors. However, I have noticed that periodically the camera entity becomes unavailable.

**Expected behavior**
The camera will not become unavailable

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/57643470/193465251-f2fde8f5-187b-4b76-8cc3-0be28988814c.png)

**Environment:**
Please provide useful information about your environment, like:
 - 2022.10b3
 - RLC-810A
 - v3.1.0.956_22041503

**Additional context**
I am attaching the log at the time of the last outage approx. 6:15 p.m

[log.txt](https://github.com/JimStar/reolink_cctv/files/9693008/log.txt)

**Comment by JimStar** [comment]
Yep, I fixed this "unavailable" for all the **sensors**, but did not investigate it for **camera** 'cause I've not seen this happening on my side with cameras..;)  
I'm going to investigate and fix this now...

One question:  
Did you open/watch any camera's livestream before this started to happen?  
Could you try to re-start the HA, don't open don't watch any camera-livestream after that, and see if this "unavailable" would still happen on your cameras?

**Comment by leroyloren** [comment]
I don't use camera so it didn't even watch. I can only see it as an error (warning) in the Records.

I use the integration clean for sensors state.

**Comment by JimStar** [comment]
Thanks!  
I'll let here know when a fixed version is released...

**Comment by JimStar** [comment]
One more question: could you please be sure you have "preload stream" disabled in your camera settings?

**Comment by leroyloren** [comment]
Yeah
![obrazek](https://user-images.githubusercontent.com/57643470/193471764-9eaf5305-0492-4f71-b30f-20c952eb7699.png)

**Comment by JimStar** [comment]
Got it, thank you!

**Comment by JimStar** [comment]
Should be fixed by **0.0.3** I've just published.  
Please feel free to re-open this if you'll still get this issue happening on your side...

**Comment by leroyloren** [comment]
v0.0.3 seems to be fine now.

Thanks.
