### ISSUE TITLE
Face detection throws an error in logs if face detection sensor entity is disabled through HA

### ISSUE THREAD

**Issue by skynet01** [JimStar/reolink_cctv#51]
**Describe the bug**
I disabled all the Face detection entities as they are not used ..yet? Now my logs are filled with errors related to this. Thought it might be good idea to report it, as I do get a lot of them (almost 200 in 2 hr period). Weird that other entities that I disabled don't create any errors (FTP, email, vehicle etc..) 

**To Reproduce**
Disable face detection entity as it's not used. 

**Expected behavior**
No error logs should be created.

**Debug log would be very helpful**
Ge the following error on pretty much all my cameras:

```
Logger: homeassistant
Source: helpers/entity.py:538
First occurred: 8:22:49 PM (197 occurrences)
Last logged: 10:47:41 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/reolink_cctv/binary_sensor.py", line 234, in handle_event
    await self._host.sensor_face_detection[self._channel].handle_event(Event(self._host.event_id, {"ai_refresh": motion_common_event_state}))
  File "/config/custom_components/reolink_cctv/binary_sensor.py", line 403, in handle_event
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 690, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Yard Cam face detected: off>
```

**Comment by JimStar** [comment]
Should be fixed in [0.0.26](https://github.com/JimStar/reolink_cctv/releases/tag/0.0.26).
