### ISSUE TITLE
Integration doesnt start at all

### ISSUE THREAD

**Issue by benek984** [JimStar/reolink_cctv#54]
Just installed this integration and after adding my NVR I only can see this error in the log

This error originated from a custom integration.

Logger: custom_components.reolink_cctv.host
Source: custom_components/reolink_cctv/host.py:187
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 15:10:01 (158 occurrences)
Last logged: 20:01:06

Error registering a webhook reolink_NVR_webhook for NVR: maybe a duplicate device-name in your setup?

I have looked for names like NVR, Reolink in my device and entities list but nothing similar to this exist.

**Comment by JimStar** [comment]
Please switch on the debug logging for this component (the config lines were in the issue-template), and attach a **full** debug log (starting with HA restart).

One more thing: if you had `reolink_dev` before, have you waited after removing it and adding this one? There is a chance a previous login-session is stuck in Reolink device for an hour, before it lets another session to start. For all this time the device would reject any login attempts from a component, before some active session finally expires...

**Comment by JimStar** [comment]
Before creating the debug-logging file, please update to the just released [0.0.27](https://github.com/JimStar/reolink_cctv/releases/tag/0.0.27). There are few stability/logging improvements in there...  
If it still has issues for you - please attach the full log file, as mentioned above.

**Comment by benek984** [comment]
I have restarted my NVR and the integration is starting now. Thank you for help. you can close this issue.

**Comment by benek984** [comment]
NVR restart is a solution.
