### ISSUE TITLE
Retrying setup: Error while trying to setup None, API had hard error

### ISSUE THREAD

**Issue by firemen2709** [JimStar/reolink_cctv#63]
Jim, 
I realize this is not your repo. i had the same exact issues when i tried your version of reolink_cctv. I firmly believe that this is happen across all HA after an reolink update. if there's any more info i can provide i will be happy to help. im not coder and am new-ish to HA. 
But after firmware update not working anymore. it did work prior to firmware update. Reolink needs to allow clients the ability to downgrade easily. 
here's my Errors:

This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: config_entries.py:395
First occurred: 4:03:33 PM (9 occurrences)
Last logged: 4:03:35 PM

Config entry 'Shed' for reolink_dev integration not ready yet: Error while trying to setup None, API had hard error; Retrying in background
Config entry 'Lisa' for reolink_dev integration not ready yet: Error while trying to setup None, API had hard error; Retrying in background
Config entry 'Front Porch' for reolink_dev integration not ready yet: Error while trying to setup None, API had hard error; Retrying in background
Config entry 'Front Door' for reolink_dev integration not ready yet: Error while trying to setup None, API had hard error; Retrying in background
Config entry 'Eagle' for reolink_dev integration not ready yet: Error while trying to setup None, API had hard error; Retrying in background

Logger: custom_components.reolink_dev
Source: helpers/update_coordinator.py:151
Integration: Reolink IP camera (documentation, issues)
First occurred: 4:05:37 PM (1 occurrences)
Last logged: 4:05:37 PM
Timeout fetching reolink.Basement.motion_states data
 
Also get this error from a reolink camera NOT on NVR
Logger: homeassistant.components.stream.stream.camera.basement
Source: components/stream/__init__.py:428
Integration: Stream (documentation, issues)
First occurred: 4:03:40 PM (21 occurrences)
Last logged: 4:38:42 PM

Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsp://****:****@192.168.2.193:554/h265Preview_01_sub

HA: 
Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221102.1 - latest

NVR:
Model
RLN8-410
Build No.
build 22102413
Hardware No.
N2MB02
Config Version
v3.0.0.0
Firmware Version
v3.1.0.211_22102413

**Comment by JimStar** [comment]
The code of the `reolink_cctv` component is **very different** from `reolink_dev`, so these logs are useless to me for analyzing the reason of your problems.  
Feel free to reopen this ticket after attaching here the **full** debug log of **this** component (if you would get similar problems with it of course). The config-lines to enable debug-logging for this component were in the ticket's template.

Take into account, that Reolink firmware update **DISABLES** ONVIF, so make sure you've **enabled these things again** in the "ports" settings section.
