### ISSUE TITLE
Problems with spotlights on cameras

### ISSUE THREAD

**Issue by echoztrip** [JimStar/reolink_cctv#64]
After telling you in another issue how well things are working, I was mucking around shortly after with the spotlight function on the cameras and they all turned on fine via home assistant BUT I'm simply unable to turn off the spotlight now no matter what I try! I've power cycled the cameras, rebooted the NVR and rebooted home assistant, and when they come back online, the spotlight comes back on automatically! I can't seem to turn off the lights via home assistant, or even the NVR or even the reolink app. It's like it's been permanently switched on.

![image](https://user-images.githubusercontent.com/72689119/202408581-a07a1c0e-2a76-4bad-9a89-7429fed449e2.png)

Do you have any cameras with spotlights and have you come across this problem?

**Comment by echoztrip** [comment]
Ahhh I think I might have worked it out. Switching on the spotlight via Home Assistant, essentially configures a 24 hour "always on" schedule for the spotlight. But switching it off doesn't change this back to what it was before (for me at least - which is "Auto").

**Comment by JimStar** [comment]
This feature on a Reolink cameras can be in 3 different modes (the screenshot from their "API guide"):

![1](https://user-images.githubusercontent.com/3421219/202539875-80a36a5b-ca1c-46a1-a2d2-c7f17ae80d5c.png)

What I see how this switch works currently (this part is the legacy of `reolink_dev`):
The switch in this component is a **switch**, which means it can have just **two** states: ON and OFF. So what this component does:
- If you select ON, the component sets the lighting-schedule "from 00:00 to 23:59", and then issues the command to the camera "set the **mode 3** with 100% brightness and **state** to **1**".
- If you switch this OFF, the component issues the command to the camera "set the **mode 1** with 100% brightness and **state** to **0**".

First of all - I don't see the **mode 3** in Reolink's API guide. If this command's parameter still switched ON the light on your cameras, then it's one more undocumented Reolink's mess. I would expect the **mode 2** in this place (and I'm going to change it to that in next version).  
But regarding the "switch OFF" behavior of this switch there could be several possibilities, and **only one** can be used obviously. Currently it just switches the `state` parameter to OFF (**0** value), and sets the `mode` parameter to **1** (alarm trigger mode).  
So I don't know what is the "Auto" mode you mentioned, but the **mode 1** looks to me like kinda "auto" too - if it's supposed to switch on the lights triggered by alarm according to Reolink's API manual... What would you expect it to set the `mode` parameter to when you switch it OFF?..

**Comment by JimStar** [comment]
BTW, if sending the "set the **mode 1** with 100% brightness and **state** to **0**" command to the camera **without resetting the schedule** did not switch OFF your light on the cameras, then it looks like another **bug** that should be reported to Reolink.

Because no matter what the schedule is set to (even if to the "whole day long") - if the `mode` is set by the `SetWhiteLed` command to **1** (which means NOT BY A SCHEDULE), the schedule **must have no effect**, and only the "alarm trigger" must affect the lights state. Moreover that the `state` is set in the command to **0** - which means the lights **must be OFF** no matter what the schedule is...  
To me it definitely looks like another Reolink mess.

**Comment by echoztrip** [comment]
Thanks Jim. I love how you put "API Guide" in quotations! hahaha

Reading through your response, I think toggling "off" in HA should set the "mode" back to "alarm trigger mode" (1 according to your screenshot from their "documentation") and "state" to 0. 

"wlAiDetectType" I imagine is where I have in _some_ of the Reolink GUI's to configure the trigger of the spotlight at night to be  "vehicle", "person" and "pet" - which is my normal condition. 

Example:

![image](https://user-images.githubusercontent.com/72689119/202559426-62994673-5e84-4252-8577-b2491ca83bf3.png)

Happy to get debugs/test/etc if you can give me a little guidance. Appreciate your attention to this project as always.

**Comment by JimStar** [comment]
> Reading through your response, I think toggling "off" in HA should set the "mode" back to "alarm trigger mode" (1 according to your screenshot from their "documentation") and "state" to 0.

But a can not change it to be this way more than it already IS right now, because this is already **exactly** how it is done in **0.0.28** and in all the previous versions of this component. I described this above...  
Just read my previous post: if this doesn't switch OFF the lights on your cameras - then this looks like a Reolink bug.

**Comment by JimStar** [comment]
What I will do in the next version - I will add the setting of the schedule to "from 00:00 to 00:00" additionally to the "switch off" command. Maybe this could workaround this Reolink's bug...

**Comment by echoztrip** [comment]
No problems. Happy to try & test.

**Comment by JimStar** [comment]
I don't have a spotlight on my cams, so could you check before I start doing this - is it possible to set the schedule manually as "from 00:00 to 00:00" or something like this to force it never schedule?  
Because I see the check in the legacy `reolink_dev` code where it doesn't allow to send equal start/end in the `SetWhiteLed` command. Not sure if I remove this restriction you would not just get errors returned by a camera in response to such attempt... The Reolink's API "documentation" as usual doesn't give a shit about this specifics...

**Comment by echoztrip** [comment]
Hey Jim,

The web interface seems to accept 00:00 to 00:00 :)

![image](https://user-images.githubusercontent.com/72689119/202627933-c000dcc8-30d8-4067-aaf7-b023d30eee5c.png)

**Comment by JimStar** [comment]
OK, thanks!

**Comment by JimStar** [comment]
Done in [0.0.29](https://github.com/JimStar/reolink_cctv/releases/tag/0.0.29).

**Comment by echoztrip** [comment]
Hey Jim, I just have 0.0.29 a go and it doesn't even turn on the light now! haha. Any logs/steps/debugging I can provide to help?

**Comment by JimStar** [comment]
Full debug log. Starting with the HA restart.

**Comment by echoztrip** [comment]
Can do - I've not done one before.  Is it just adding this to my configuration.yaml? 

logger:
   default: debug

**Comment by JimStar** [comment]
Please look at the issue template. There a lines you need in the config.

**Comment by echoztrip** [comment]
Got it. Trying now

**Comment by echoztrip** [comment]
It was too big for pastebin ... so here is a zip. 
I toggled the "backdoor" camera spotlight switch in HA around 19:22 and also 19:25/19:26. 
[log.zip](https://github.com/JimStar/reolink_cctv/files/10039513/log.zip)

**Comment by JimStar** [comment]
Normal programmer's workflow:

Looking at the Reolink API "documentation" regarding "what mode to set in the `SetWhiteLed` command":

<img width="650" alt="Screen Shot 2022-11-18 at 21 38 28" src="https://user-images.githubusercontent.com/3421219/202658371-d289cd46-fe92-47b5-b4e5-fc474b7a13bb.png">

"*OK, I need to set it for specific periods, I need a mode 2*".  
Sets a `mode: 2` in the `SetWhiteLed` command parameters. Gets a response to that command from the Reolink device:

<img width="296" alt="Screen Shot 2022-11-18 at 21 36 03" src="https://user-images.githubusercontent.com/3421219/202658741-a9336842-9ea2-4af1-8af8-47ffe7918d43.png">

"*OK, something that Reolink device doesn't like, let's look at their API docs for the detailed description of the code `-13`*":

<img width="657" alt="Screen Shot 2022-11-18 at 21 35 04" src="https://user-images.githubusercontent.com/3421219/202658948-31670125-b51e-40e4-a4ce-40d971cc8aac.png">

"*F@#%&#!*"..

**Comment by echoztrip** [comment]
hahahaha.   *shakes fist*

I'm far from a programmer, but is it possible they specify 0, 1 and 2 in the doco, but it's actually 1, 2 and 3? And if you're specifying mode 2, that could be the alarm trigger mode and expecting additional parameters? 

Showing my naivety, is there an "easy" way for me to manually craft/send the API commands to try a few things for you more real time? And if there is, would it have any value?

**Comment by JimStar** [comment]
This is what I'm thinking now - there must be still "3". Looks like the `reolink_dev` programmer learned this hard way too..;)

Will release a quick-fix version soon...

**Comment by JimStar** [comment]
Done in the [0.0.30](https://github.com/JimStar/reolink_cctv/releases/tag/0.0.30).

**Comment by echoztrip** [comment]
Will update and report back with debug logs if issues!

**Comment by echoztrip** [comment]
Success ;) Able to switch it on and off ...on demand! 

Is there a way to switch it back to "Auto" (with the relevant AI settings?)

**Comment by JimStar** [comment]
Actually it **IS** set to "auto" when switching off: it sends the command with the `mode: 1` parameter which according to their "documentation" is "auto"...

Looks like these docs are just useless, and all needs to be reverse-engineered. It's not trivial to play with manually sending/debugging these commands for non-IT person... But you can google how to do this if you still like to dig into this..;)

**Comment by echoztrip** [comment]
Oh and looking at it, when "off" it does the 00:00 - 00:00 which is why I thought it wasn't doing Auto :) 

No stress either way, have enjoyed the interaction regardless :)

**Comment by JimStar** [comment]
You can look at [their doc](https://github.com/JimStar/reolink_ip/raw/0.0.30/doc/Camera%20HTTP%20API%20User%20Guide_v7.pdf), somewhere on page 29: you could play with sending those commands from camera's web UI, and see what commands are sent to the camera by the browser...

**Comment by echoztrip** [comment]
Love how they have the "Jason" typos :)

All I seem to be able to find myself is a repeating sequence of this when toggling options:

![image](https://user-images.githubusercontent.com/72689119/202825468-56f105c2-5591-4630-8526-016cfa1ac45c.png)

and the payloads are encrypted?

![image](https://user-images.githubusercontent.com/72689119/202825617-677a95b9-2069-4e6c-a5ec-9066672d7c14.png)

It's all good though Jim, thanks again for looking at this issue for me.

**Comment by echoztrip** [comment]
It's always when I write something I realise it's dumb. I'll switch to http only and try again :P

**Comment by echoztrip** [comment]
Yeah no joy. Not sure if you've seen this? https://www.reddit.com/r/reolinkcam/comments/xpcxq6/reolink_camera_api_user_guide_v7_update_in_sept/
Seems like a representative from Reolink is there and updates it every few months and looks for feedback.
