### ISSUE TITLE
Object detection sensors not working with direct connection to cameras

### ISSUE THREAD

**Issue by chris-a-j** [JimStar/reolink_cctv#8]
Creating this ticket as I understand that you have not yet tested direct connections

Coming from the reolink_dev integration, I completely removed this from HACS, restarted HA and proceeded to install this new integration. I have my cameras connected to a Synology NVR but I’ve set this up to connect to the cameras directly. 

Problem I am experiencing is that when the cameras (510A) detect an object (as viewed in Synology Surveillance Station), this does not trigger the entity in home assistant - I.e it just permanently remains as ‘clear’.

I’ve set this up in the same way as I did with reolink_dev and haven’t changed any other settings elsewhere. 

HA is 2022.9.7, RLC-510A v3.1.0.951_22041567. All entities available and camera stream visible, but binary sensors not triggered when they should. 

Any ideas where to start to troubleshoot?

**Comment by JimStar** [comment]
If I understood correctly - in #5 a guy has a direct connection too, and works OK...

Could you please enable debug-logging, and attach here a full log (starting from the HA restart and having at least one motion event during that)...

```
logger:
  default: warning
  logs:
    custom_components.reolink_cctv: debug
    reolink_ip: debug
```

**Comment by JimStar** [comment]
My quick guess (maybe I'm wrong):  
I don't know the maximum amount of subscriptions that is provided by ONVIF in RLC-510A cameras. For example, for Reolink RLN8-410 NVR - it is just maximum 3.  
So, if your camera is already connected to Synology, maybe the Synology server has already subscribed to ONVIF events on that camera, and when `reolink_cctv` tries to subscribe too, the camera could reject it because its just one subscription is already used by Synology...

Just a guess... maybe there is some other reason... I need the debug-logs to investigate it further...

**Comment by chris-a-j** [comment]
Please see attached log as requested. 
[home-assistant.log](https://github.com/JimStar/reolink_cctv/files/9709991/home-assistant.log)

**Comment by chris-a-j** [comment]
Sorry about that. I posted it in the golden few minutes that I have before I put my son to bed :)
 I will post another copy tomorrow with motion events triggered.

**Comment by JimStar** [comment]
No rush. ;)  
BTW, I'm in New Zealand, so our timings could be quite different... Don't be surprised if there are delays with my answers...

**Comment by JimStar** [comment]
Just in case: please update to a new **0.0.5** version, before making another debug-log...

**Comment by Schnabulation** [comment]
I'm not quite sure if this is the same issue but all my motion sensors show as "unavailable". I had the same issue with the previous Reolink integration from fwestenberg and was hoping that your integration would work. It seems it's related to my firmware upgrade to V3.1.x.

![grafik](https://user-images.githubusercontent.com/1053834/194030470-a9636634-1bf5-43b5-9d95-d5460c29d977.png)

I did find this entry in my log - which is rather odd because the camera-entity works perfectly fine:

`2022-10-05 11:38:36.987 ERROR (MainThread) [reolink_ip.api] Host 192.168.100.24:443: connection error: Cannot connect to host 192.168.100.24:8000 ssl:default [Connect call failed ('192.168.100.24', 8000)].`

**Comment by Schnabulation** [comment]
EDIT: Please ignore my previous post. I noticed that the firmware upgrade disabled the ONVIF port. After I enabled it the motion sensors became available again.

**Comment by chris-a-j** [comment]
Ok, here is the new log. I rebooted HA, let everything initialise, then walked outside infront of my "Front" camera. I received a notification from Surveillance Station that there was a person detected. This means that motion was definitely triggered by the camera's AI, but still the appropriate entity status did not change. Let me know what you think, thanks!
[home-assistant.log](https://github.com/JimStar/reolink_cctv/files/9714898/home-assistant.log)

**Comment by JimStar** [comment]
Interesting issue.  
I can see in your log that all the webhooks for each of three cameras are **successfully subscribed**, and all cameras respond with confirmation.  
But none of cameras **never** sent any notifications to HA. Which, taking into account nobody else reported anything similar, looks like some issue with your particular setup.

If the `reolink_dev` worked for you and you got notified - then my guess it might be that it never got any ONVIF notifications from cameras either, but you just had the **polling** set up for it with very low period, and it constantly bombed all cameras with "what's happening?" requests. If you'd like to confirm this - you could make the same debug-log with `reolink_dev`... but most likely - it is the case.  
This component works much more efficient, and it relies on cameras' ONVIF to be working correctly, and it still will poll (with period set up), but only in the case if subscription **failed**. In your case all cameras report that the subscription was successful, thus it just checks from time to time (with the period set up) the subscription state, sees it's OK, and doesn't poll.

It would be interesting to investigate what's the problem on your side with the subscription, and I could improve the above algorithm accordingly if needed. My guess - maybe the Synology somehow interferes with Reolink subscription functionality... Maybe Reolink cameras' firmware goes crazy if asked to subscribe twice for different webhook from different hosts/addresses... maybe something else...  
Is it possible for you to test it by exclusion method?.. E.g. try to disable Synology, connect integration to only **one** camera, and see what's happening?..

**Comment by chris-a-j** [comment]
Yes, I can certainly investigate further.

One thing that has just crossed my mind - could this be a firewall issue? The cameras are on a VLAN that prevents them establishing a connection to anything outside of the VLAN subnet - i.e. isolated to the VLAN. However, I didn't actually think this would be a problem, as my understanding is that Home Assistant is the one that establishes the connection to the camera and not the other way around.

**Comment by JimStar** [comment]
> that Home Assistant is the one that establishes the connection to the camera and not the other way around.

No that's not the case for ONVIF notifications, it's only the case for command-requests that the component sends to cameras.  
But when a camera sends a notification to HA - it initiates the connection **from camera** to the HA webhook-address.  
So your assumption about isolated VLAN cameras could not connect to HA - maybe correct...

**Comment by chris-a-j** [comment]
Ok, we've cracked it. I added a rule to pfsense to allow cameras to connect to Home Assistant IP address only, walked outside and bingo - person detected entity is triggered.

Sorry to have troubled you with all of that. In the end it was my firewall rules that were too strict!

**Comment by JimStar** [comment]
Cool!

**Comment by Barma-lej** [comment]
Hi Jim. I have 3 cameras (1x E1 Zoom, 2x RLC-510WA) with direct connection in the same network.

Problem is that when the cameras detect an object, this does not trigger the entity in home assistant - I.e it just permanently remains as ‘clear’.

The external and internal addresses of HA are the same (https://xxxxxx.duckdns.org:port/).

Here is my log:   
[e1_zoom_rlc_510wa.txt](https://github.com/JimStar/reolink_cctv/files/10087382/e1_zoom_rlc_510wa.txt)

**Comment by JimStar** [comment]
I see in your logs you're trying to use the https webhook for motion notifications. Please read the component's readme carfully. It is mentioned in there:

*For the motion detection to work, Home Assistant must be reachable via http from your local network. So when using https internally, motion detection will not work at this moment.*

Reolink firmware is not able to send ONVIF notifications to https webhooks. You need it to be reachable locally by http from your cameras to have Reolink's ONVIF notifications working...  
Feel free to let me know if it would not work for you with http either.

**Comment by cvjensen** [comment]
> I see in your logs you're trying to use the https webhook for motion notifications. Please read the component's readme carfully. It is mentioned in there:
> 
> _For the motion detection to work, Home Assistant must be reachable via http from your local network. So when using https internally, motion detection will not work at this moment._
> 
> Reolink firmware is not able to send ONVIF notifications to https webhooks. You need it to be reachable locally by http from your cameras to have Reolink's ONVIF notifications working... Feel free to let me know if it would not work for you with http either.

Hi @JimStar , could there be other reasons that I'm having trouble with ONVIF notifications?
I've just installed nginx so that my HA is accessible using http internally in my network. After this I removed the integration and readded the camera but I still seem to have problems with the person_detected sensor .
Other ideas?

**Comment by JimStar** [comment]
Use Wireshark to track where the ONVIF packets from your device are lost.

**Comment by cvjensen** [comment]
Alright .

quick question - when I add the integration , is it then ok to choose https and 443?
![image](https://user-images.githubusercontent.com/9024493/204348939-40c66fcb-6d9e-4ba2-990c-0b835a4f2edc.png)

Or doesn't have anything to do with ONVIF and the sensors that require http access ?

**Comment by JimStar** [comment]
Whatever you choose here - doesn't matter for the ONVIF communication: the component will try to send ONVIF requests to your device's ONVIF port **over http**.

**Comment by cvjensen** [comment]
Just tried to run wireshark with the following and then go out and make my camera detect a person.

![image](https://user-images.githubusercontent.com/9024493/204456831-ee263561-5d02-4652-8b2d-09897a380b66.png)

I then tried to restart the camera and readd the integration and did another detection while running wireshark

![image](https://user-images.githubusercontent.com/9024493/204458436-d03d331d-db75-419e-a78d-f026f760b089.png)

.0.56 == Camera
.0.31 == HA on my rpi

Still no luck . Just to make it clear im just running wireshark on my PC and not on any promiscuous port .

If you want me to create an issue just say so 😄

**Comment by JimStar** [comment]
This is not this component's issue. This is some networking issue on your side.

**Comment by cvjensen** [comment]
> This is not this component's issue. This is some networking issue on your side.

I'm not trying to start a blame game , I was just asking for help .

**Comment by Schnabulation** [comment]
Just a little note: I noticed that when I upgraded the firmware of my Reolink devices it seems that ONVIF got **disabled**! Maybe check that.

**Comment by cvjensen** [comment]
Hi @Schnabulation , thanks for your hint . 
I have checked and tried to disable , restart and enable again
Now it looks like this:

![image](https://user-images.githubusercontent.com/9024493/204487573-cd9a577f-af0d-4f50-9bd3-23a5df1a9f50.png)
![image](https://user-images.githubusercontent.com/9024493/204487632-9e3dd76d-9c0e-431a-bd82-3c36745c26f2.png)

I have the most simple home network with a 192.168.0.0/24 , no vlans .

I'm now wondering , is ONVIF using hostnames / DNS ? or is it relying on IP's?

**Comment by JimStar** [comment]
> I'm not trying to start a blame game , I was just asking for help .

I'm not either. I'm just saying that you need to track why the ONVIF SWN packets do not come through in your network... It's hard for me to guess from here...

**Comment by Schnabulation** [comment]
In Home Assistant, what do you have set under Settings --> System --> Network? Can you reach Home Assistant by opening http://192.168.0.31 inside your LAN?

**Comment by cvjensen** [comment]
> In Home Assistant, what do you have set under Settings --> System --> Network? Can you reach Home Assistant by opening http://192.168.0.31 inside your LAN?

I have a static lease: : eth0 (192.168.0.31/24
Then I have my public https: https://abc.duckdns.org:8123/
And my local: http://raspberrypi:8123/

No I cant access http on port 80 but I can on 8123

**Comment by cvjensen** [comment]
Alright so the camera is trying to use the DNS name in Settings --> System --> Network --> Local . 

I dont use DNS internally in my network so I just tried to specify HA's IP in the Home Assistant URL Internal - http of course.

And now it seems to be working. This is so great!

**Comment by joneshf** [comment]
> Ok, we've cracked it. I added a rule to pfsense to allow cameras to connect to Home Assistant IP address only, walked outside and bingo - person detected entity is triggered.
> 
> Sorry to have troubled you with all of that. In the end it was my firewall rules that were too strict!

I have a similar setup, but using an NVR rather than direct connections to cameras. Like you, allowing traffic from the NVR to Home Assistant in my firewall also worked for me. Thanks for following up on this being the solution for you!

While I can set a firewall rule to only allow the (statically defined) IPs of the NVR and Home Assistant, I'd also like to minimize how many ports are open for this rule. I can't seem to figure out which ports are necessary for these notifications. Did you allow all ports in your firewall, or were you able to specify only certain ports that allowed the notifications to make it from a camera to Home Assistant?
