### ISSUE TITLE
Camera feed takes a long time to load

### ISSUE THREAD

**Issue by Schnabulation** [JimStar/reolink_cctv#85]
**Describe the bug**
Whenever I open Lovelace it takes a long time for the camera feeds to load. Sometimes it even breaks and does not show the feed at all.

**To Reproduce**
Everytime I open Lovelace.

**Expected behavior**
If I remember correctly the Reolink integration of [fwestenberg](https://github.com/fwestenberg/reolink_dev) did not have this issue. It should immediately show the camera feeds.

**Debug log would be very helpful**
If necessary I'll provide the log.

**Screenshots**
![Cameras_long_load](https://user-images.githubusercontent.com/1053834/204313634-0fadb657-a1c4-4cab-a5d7-2b1af5c64ee5.jpg)

**Environment:**
 - Home Assistant version: latest (Home Assistant 2022.11.4)
 - Reolink NVR/camera model: 4x Reolink E1 Outdoor
 - NVR/camera firmware: latest from Reolink support

**Comment by JimStar** [comment]
The component just provides a link to the stream, anything else is done by HA and your browser. So this is not the component's issue. I can't affect this from the component side other than providing different links to different video streams...

The reason why it worked differently with other component could be just different settings. Either the "sub" stream type, video encoding, or you could set "images" type in this component's config (maybe that mode you seen by default in other component?)...

**Comment by Schnabulation** [comment]
What settings would you suggest for max. performance? I have set it as follows:

![Screenshot 2022-11-29 125823](https://user-images.githubusercontent.com/1053834/204524261-1caa800d-ab56-4810-9aa5-b5dd2913b203.jpg)

**Comment by JimStar** [comment]
As I said, try images, maybe it would be better for you... There is nothing that could be improved on the plugin side regarding this  - as I said it just provides stream-links to HA....
