### ISSUE TITLE
Documentation of config flow properties

### ISSUE THREAD

**Issue by yolani** [JimStar/reolink_cctv#97]
Any chance we can get some documentation about the available options in the config flow, I mean I can guess most of them, but for example one is simply called timeout... Timeout of what? ;-)

**Comment by JimStar** [comment]
It is not called "timeout". It is called "Connection timeout", which is clear enough IMHO: the attempt to connect a Reolink device will timeout after this amount of seconds...  
How would you like this setting to be named otherwise?

**Comment by yolani** [comment]
![image](https://user-images.githubusercontent.com/219931/205432385-aea1c4e4-2322-4332-bdff-c708ef9dc6aa.jpeg)

Actually it's only called timeout on my side (German language setting). 

Also I was wondering how the force-off timeout for the motion sensor exactelly behaves. Does is reset the HA motion sensor even if the camera does not report "no motion"?

**Comment by JimStar** [comment]
> Does is reset the HA motion sensor even if the camera does not report "no motion"?

Yes.

**Comment by JimStar** [comment]
> Actually it's only called timeout on my side (German language setting).

Feel free to create a PR with your language files improved.

**Comment by yolani** [comment]
Will do, thx anyway.
