### ISSUE TITLE
Database Records

### ISSUE THREAD

**Issue by tempus2016** [JimStar/reolink_cctv#99]
**Describe the bug**
The integration has a lot of stored records. Is this a bug or just because there is a lot of things being monitored and recorded?

**To Reproduce**
Use the SQLite addon to view your database.
Click on the events table in SQLite Web.
Click on Query.
Type the following SQL query:
```
SELECT
  COUNT(*) as cnt,
  SUM(LENGTH(event_data)) as bytes,
  event_type
FROM events
GROUP BY event_type
ORDER BY cnt DESC
```

**Screenshots**
<img width="833" alt="Screenshot 2022-12-03 at 10 37 52" src="https://user-images.githubusercontent.com/40920327/205436814-4b463775-2e2e-41d5-80fe-6e826a4cb710.png">

**Environment:**
Please provide useful information about your environment, like:
Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

**Additional context**
Maybe any other context about the problem here.

**Comment by JimStar** [comment]
The integration does not store these records. It just uses the `reolink_NVR_webhook` event. Looks like HA just takes a record every time the event happens...
